// The weekly DS precedence check, end to end on fakes: the end-of-day check
// compares the component index and the registry's props with the Figma
// library, the next morning run posts one thread in #plus-universal with a
// card that files or updates one intake, and a reply disputes an item.
//
// The fixtures are drawn from the manual first pass of this check (#339): the
// five button sets that split what code keeps as one `fill` prop, a code
// component with no Figma set, and a component on which both sides agree.
import { describe, it } from "node:test";
import assert from "node:assert/strict";

import type { FigmaComponentsResponse } from "../src/figma/client";
import { createInMemoryFigma } from "../src/figma/in-memory";
import {
  findDisagreements,
  inFlightComponents,
  liveLibraryFrom,
  losingSide,
  parseComponentIndex,
  type PrecedenceRegistry,
} from "../src/ds-precedence/compare";
import { disputedItems, PRECEDENCE_MARKER, precedenceOperations } from "../src/ds-precedence/report";
import {
  disputePrecedenceItems,
  followRestagedCard,
  postPrecedenceReport,
  precedenceChannel,
  type DisputeDeps,
  runPrecedenceCheck,
  PRECEDENCE_CARD_TTL_MS,
  type CheckDeps,
  type PostedThread,
  type PostDeps,
  type PrecedenceReport,
} from "../src/ds-precedence/jobs";
import {
  handleDsPrecedenceReply,
  isDsPrecedenceCandidate,
  isWeeklyPrecedenceThread,
  recordPrecedenceRestageFor,
} from "../src/ds-precedence/env";
import type { SlackMessageEvent } from "../src/slack/types";
import type { Env } from "../src/types";
import { resolveSignal, type GateSignal } from "../src/gate/index";
import { createInMemoryThreadState, proposalSlot, type PendingProposal } from "../src/thread-state/index";

const FILE_KEY = "zAecJNRdvJzAUOcjV32tRX";
const REPO = "BilLogic/plus-uno";
const CHANNEL = "C072E8SFLKV";
const MEMBERS = ["U0MEMBER1", "U0MEMBER2"];
const OUTSIDER = "U0OUTSIDE";

// ── Fixtures (#339) ──────────────────────────────────────────────────────────

const INDEX_MD = `<!-- DO NOT EDIT BY HAND. Generated by npm run generate:agent -->
# PLUS DS — Components

## UI components (4)

- [Button](../../src/components/actions/Button/index.md)
- [Tooltip](../../src/components/overlays/Tooltip/index.md)
- [TreeSelect](../../src/components/forms-and-inputs/TreeSelect.md)
- [Scale](../../src/components/forms-and-inputs/RadioButtonGroup.md) — alias of \`RadioButtonGroup\`, same props
`;

const variant = (name: string, node: string, set: string, setNode: string) => ({
  key: `k-${node}`,
  name,
  node_id: node,
  containing_frame: { name: "Buttons", nodeId: "1:1", containingComponentSet: { name: set, nodeId: setNode } },
});

const buttonSet = (set: string, setNode: string, n: number) => [
  variant("size=small, style=primary, state=rest (default)", `${n}:1`, set, setNode),
  variant("size=medium (default), style=secondary, state=hover", `${n}:2`, set, setNode),
  variant("size=large, style=primary, state=rest (default)", `${n}:3`, set, setNode),
];

/** The library: four fill sets for the one Button, a Tooltip that agrees, an
 *  internal part, and no TreeSelect at all. */
const LIBRARY: FigmaComponentsResponse = {
  meta: {
    components: [
      ...buttonSet("Filled buttons", "33:2470", 100),
      ...buttonSet("Tonal buttons", "979:20977", 200),
      ...buttonSet("Outlined buttons", "33:2471", 300),
      ...buttonSet("Text buttons", "33:2472", 400),
      variant("placement=top", "500:1", "Tooltip", "300:1"),
      variant("placement=bottom", "500:2", "Tooltip", "300:1"),
      variant("depth=0", "600:1", "_tree_select", "600:9"),
    ],
  },
};

const set = (name: string, node: string, fill: string) => ({
  name,
  componentSetNodeId: node,
  codeDefaults: { fill },
  variantProps: { size: "size", style: "style", state: "state" },
  variantValueMap: { size: { small: "small", "medium (default)": "medium", large: "large" } },
  status: "verified",
});

const REGISTRY: PrecedenceRegistry = {
  components: {
    Button: {
      code: {
        mdxPath: "design-system/src/components/actions/Button/Button.mdx",
        props: {
          style: { type: "enum", values: ["primary", "secondary"] },
          fill: { type: "enum", values: ["filled", "tonal", "outline", "ghost", "text"] },
          size: { type: "enum", values: ["small", "medium", "large"] },
          disabled: { type: "boolean" },
        },
      },
      figma: {
        sets: [
          { name: "Buttons docs page (MDX link)", componentSetNodeId: "3497:19482", status: "docs-page", isComponentSet: false },
          set("Filled buttons", "33:2470", "filled"),
          set("Tonal buttons", "979:20977", "tonal"),
          set("Outlined buttons", "33:2471", "outline"),
          set("Text buttons", "33:2472", "text"),
        ],
      },
    },
    Tooltip: {
      code: {
        mdxPath: "design-system/src/components/overlays/Tooltip/Tooltip.mdx",
        props: { placement: { type: "enum", values: ["top", "bottom"] } },
      },
      figma: { sets: [{ name: "Tooltip", componentSetNodeId: "300:1", status: "verified" }] },
    },
    TreeSelect: {
      code: { mdxPath: "design-system/src/components/forms-and-inputs/TreeSelect.mdx" },
      figma: { sets: [{ name: "_tree_select", componentSetNodeId: "600:9", status: "unpublished", isComponentSet: false }] },
    },
  },
};

function check(inFlight: ReadonlySet<string> = new Set()) {
  return findDisagreements({
    index: parseComponentIndex(INDEX_MD),
    registry: REGISTRY,
    library: liveLibraryFrom(LIBRARY),
    fileKey: FILE_KEY,
    repo: REPO,
    inFlight,
  });
}

// ── The comparison ───────────────────────────────────────────────────────────

describe("the comparison", () => {
  it("the rule decides the loser: code, then the BS4 library, then the spec pages", () => {
    assert.equal(losingSide("code", "library"), "library");
    assert.equal(losingSide("spec-pages", "library"), "spec-pages");
    assert.equal(losingSide("code", "spec-pages"), "spec-pages");
  });

  it("reads the index as the existence list, aliases left out", () => {
    assert.deepEqual(
      parseComponentIndex(INDEX_MD).map((e) => [e.name, e.docPath]),
      [
        ["Button", "design-system/src/components/actions/Button/index.md"],
        ["Tooltip", "design-system/src/components/overlays/Tooltip/index.md"],
        ["TreeSelect", "design-system/src/components/forms-and-inputs/TreeSelect.md"],
      ],
    );
  });

  it("reports Button's fill-as-sets against fill-as-prop, with Figma losing", () => {
    const button = check().filter((d) => d.component === "Button");
    assert.equal(button.length, 1, JSON.stringify(button));
    const [d] = button;
    assert.equal(d!.kind, "prop-as-sets");
    assert.equal(d!.loser, "library");
    assert.equal(d!.winner, "code");
    assert.match(d!.summary, /`Button\.fill` is one prop in code/);
    assert.match(d!.summary, /Filled buttons/);
    assert.match(d!.summary, /`ghost` has no set/);
    assert.equal(d!.codeUrl, `https://github.com/${REPO}/blob/main/design-system/src/components/actions/Button/index.md`);
    assert.match(d!.figmaUrl, /node-id=33-2470/);
  });

  it("reports a component in code that the library does not have", () => {
    const tree = check().filter((d) => d.component === "TreeSelect");
    assert.equal(tree.length, 1);
    assert.equal(tree[0]!.kind, "missing-in-figma");
    assert.equal(tree[0]!.loser, "library");
    assert.equal(tree[0]!.figmaUrl, `https://www.figma.com/design/${FILE_KEY}`);
  });

  it("does not report a component on which both sides agree", () => {
    assert.deepEqual(check().filter((d) => d.component === "Tooltip"), []);
  });

  it("reports values an axis lacks, after the registry's value map", () => {
    const registry = structuredClone(REGISTRY);
    registry.components.Tooltip!.code!.props = { placement: { type: "enum", values: ["top", "bottom", "start"] } };
    const found = findDisagreements({
      index: parseComponentIndex(INDEX_MD),
      registry,
      library: liveLibraryFrom(LIBRARY),
      fileKey: FILE_KEY,
      repo: REPO,
      inFlight: new Set(),
    }).filter((d) => d.component === "Tooltip");
    assert.equal(found.length, 1);
    assert.equal(found[0]!.kind, "axis-values");
    assert.match(found[0]!.summary, /`start`/);
    // Button's `size` maps "medium (default)" to medium, so it is not reported.
    assert.equal(check().some((d) => d.component === "Button" && d.kind === "axis-values"), false);
  });

  it("leaves out a component a library publish is still carrying, where code follows", () => {
    const inFlight = inFlightComponents(
      [{ implement: "Button, Tooltip" }],
      [
        {
          created: [],
          modified: [{ key: "k", name: "placement=top", description: "", nodeId: "500:1", containingFrame: "Tooltip", setNodeId: "300:1" }],
          deleted: [],
        },
      ],
      REGISTRY,
    );
    assert.deepEqual([...inFlight].sort(), ["Button", "Tooltip"]);
    assert.deepEqual(check(inFlight).map((d) => d.component), ["TreeSelect"]);
  });
});

// ── The jobs ─────────────────────────────────────────────────────────────────

function kv<T>(initial: T) {
  const box = { value: initial, writes: 0 };
  return {
    box,
    store: {
      read: async () => box.value,
      write: async (v: T) => {
        box.value = v;
        box.writes += 1;
      },
    },
  };
}

function checkDeps(library: FigmaComponentsResponse, report = kv<PrecedenceReport | null>(null)) {
  const figma = createInMemoryFigma();
  figma.seedFile(FILE_KEY, { components: library });
  const deps: CheckDeps = {
    github: { indexMarkdown: async () => INDEX_MD, registry: async () => REGISTRY },
    figma,
    report: report.store,
    inFlight: async () => new Set<string>(),
    fileKey: FILE_KEY,
    repo: REPO,
    now: () => Date.UTC(2026, 9, 2, 22, 0),
    runDate: "2026-10-02",
  };
  return { deps, report };
}

/** A library on which every component agrees: Button as one set with a fill
 *  axis, and TreeSelect present. */
const AGREEING: FigmaComponentsResponse = {
  meta: {
    components: [
      variant("size=small, style=primary, fill=filled", "1:1", "Button", "9:1"),
      variant("size=medium, style=secondary, fill=tonal", "1:2", "Button", "9:1"),
      variant("size=large, style=primary, fill=outline", "1:3", "Button", "9:1"),
      variant("size=large, style=primary, fill=ghost", "1:4", "Button", "9:1"),
      variant("size=large, style=primary, fill=text", "1:5", "Button", "9:1"),
      variant("placement=top", "500:1", "Tooltip", "300:1"),
      variant("placement=bottom", "500:2", "Tooltip", "300:1"),
      variant("depth=0", "600:1", "Tree Select", "600:10"),
    ],
  },
};

interface Post {
  text: string;
  blocks?: unknown[];
  thread_ts?: string;
}

function postDeps(report: PrecedenceReport | null, openIntake: { number: number; url: string } | null) {
  const posts: Post[] = [];
  const staged: PendingProposal[] = [];
  const reportBox = kv<PrecedenceReport | null>(report);
  const threadBox = kv<PostedThread | null>(null);
  const recorded: PostedThread[] = [];
  let n = 0;
  const deps: PostDeps = {
    report: reportBox.store,
    recordThread: async (thread) => {
      recorded.push(thread);
      await threadBox.store.write(thread);
    },
    members: async () => [...MEMBERS],
    openIntake: async () => openIntake,
    post: async (message) => {
      posts.push(message);
      n += 1;
      return { ok: true, ts: `1759500000.00000${n}` };
    },
    stage: async (proposal) => {
      staged.push(proposal);
    },
    channel: CHANNEL,
    now: () => Date.UTC(2026, 9, 5, 14, 0),
  };
  return { deps, posts, staged, reportBox, threadBox, recorded };
}

describe("the end-of-day check", () => {
  it("keeps the disagreements for the morning", async () => {
    const { deps, report } = checkDeps(LIBRARY);
    const result = await runPrecedenceCheck(deps);
    assert.equal(result.found, 2);
    assert.deepEqual(report.box.value?.items.map((i) => i.component), ["Button", "TreeSelect"]);
  });

  it("a clean week keeps nothing, and clears a report nobody posted", async () => {
    const stale = kv<PrecedenceReport | null>({ checkedAt: "x", items: [] as PrecedenceReport["items"] } as PrecedenceReport);
    const { deps, report } = checkDeps(AGREEING, stale);
    const result = await runPrecedenceCheck(deps);
    assert.equal(result.found, 0);
    assert.equal(report.box.value, null);
  });

  it("an empty or near-empty library skips the week rather than reporting every component missing", async () => {
    // Nothing at all; one indexed component of three; and a library padded
    // with sets the index does not list (icons), which count for nothing.
    const icons = Array.from({ length: 40 }, (_, i) => variant(`size=${i}`, `9${i}:1`, `Icon ${i}`, `9${i}:9`));
    for (const components of [[], LIBRARY.meta!.components!.slice(0, 1), icons]) {
      const waiting = { checkedAt: "2026-09-25T22:00:00.000Z", items: [] } as unknown as PrecedenceReport;
      const stale = kv<PrecedenceReport | null>(waiting);
      const { deps, report } = checkDeps({ meta: { components } }, stale);
      const result = await runPrecedenceCheck(deps);
      assert.equal(result.found, 0);
      assert.match(result.summary, /week skipped/);
      assert.equal(report.box.writes, 0, "a report still waiting for its morning is left as it is");
      assert.equal(report.box.value, waiting);
    }
  });

  it("a dry run compares and writes nothing", async () => {
    const { deps, report } = checkDeps(LIBRARY);
    await runPrecedenceCheck(deps, { dryRun: true });
    assert.equal(report.box.writes, 0);
  });

  it("under EST, Friday's check runs on Saturday and labels the week with Friday, its run's date", async () => {
    // Friday 2026-12-04 is swept at Saturday 00:00 EST, 05:00 UTC, and the
    // check, deferred on a budget stop, runs at 05:10 UTC.
    const { deps, report } = checkDeps(LIBRARY);
    await runPrecedenceCheck({ ...deps, now: () => Date.UTC(2026, 11, 5, 5, 10), runDate: "2026-12-04" });
    const morning = postDeps(report.box.value, null);
    await postPrecedenceReport(morning.deps);
    assert.match(morning.posts[0]!.text, /\(2026-12-04\)/);
    assert.equal(morning.recorded[0]!.weekOf, "2026-12-04");
    assert.match(JSON.stringify(morning.staged[0]!.operations), /Week of 2026-12-04/);
  });

  it("a report kept before the run's date was recorded is labelled with its check's date", async () => {
    const kept = { checkedAt: "2026-09-25T22:00:00.000Z", items: (await weekReport()).items };
    const morning = postDeps(kept, null);
    await postPrecedenceReport(morning.deps);
    assert.match(morning.posts[0]!.text, /\(2026-09-25\)/);
  });
});

async function weekReport(): Promise<PrecedenceReport> {
  const { deps, report } = checkDeps(LIBRARY);
  await runPrecedenceCheck(deps);
  return report.box.value!;
}

describe("the morning post", () => {
  it("lands where pickDestination sends a design-system finding: #plus-universal, never #plus-design", () => {
    assert.equal(precedenceChannel({ plusUniversal: CHANNEL, plusDesign: "C0DESIGN" }), CHANNEL);
    assert.equal(precedenceChannel({ plusDesign: "C0DESIGN" }), null, "no fallback to another channel");
  });

  it("a clean week posts nothing", async () => {
    const { deps, posts, staged } = postDeps(null, null);
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, false);
    assert.deepEqual(posts, []);
    assert.deepEqual(staged, []);
  });

  it("posts one thread in #plus-universal: the list, then a card that files one intake", async () => {
    const { deps, posts, staged, reportBox, threadBox } = postDeps(await weekReport(), null);
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, true);
    assert.equal(posts.length, 2);
    const [list, card] = posts;
    assert.equal(list!.thread_ts, undefined);
    assert.match(list!.text, /1\.\*? .*Button/);
    assert.match(list!.text, /2\.\*? .*TreeSelect/);
    assert.match(list!.text, /BS4 Foundation library/);
    assert.match(list!.text, /dispute 2/);
    assert.equal(card!.thread_ts, "1759500000.000001");

    assert.equal(staged.length, 1);
    const p = staged[0]!;
    assert.deepEqual(p.confirmers, MEMBERS);
    assert.equal(p.ttlMs, PRECEDENCE_CARD_TTL_MS);
    assert.equal(p.onCancel, undefined);
    assert.equal(p.proposalTs, "1759500000.000002");
    assert.equal(p.replyTs, "1759500000.000001");
    assert.equal(p.operations?.length, 1);
    assert.equal(p.operations![0]!.toolName, "github_issue_create");
    const body = String(p.operations![0]!.input.body);
    assert.ok(body.startsWith(PRECEDENCE_MARKER));
    assert.match(body, /Button/);
    assert.match(body, /TreeSelect/);

    assert.equal(reportBox.box.value, null, "the report is handed off");
    assert.equal(threadBox.box.value?.ts, "1759500000.000001");
  });

  it("updates an open weekly intake in place rather than filing a second", async () => {
    const { deps, staged } = postDeps(await weekReport(), { number: 900, url: `https://github.com/${REPO}/issues/900` });
    await postPrecedenceReport(deps);
    const ops = staged[0]!.operations!;
    assert.equal(ops.length, 1);
    assert.equal(ops[0]!.toolName, "github_issue_update");
    assert.equal(ops[0]!.input.issue_number, 900);
    assert.match(String(ops[0]!.input.comment), /TreeSelect/);
    assert.equal(ops.some((o) => o.toolName === "github_issue_create"), false);
  });

  it("records the list thread before its card, so a card that fails still leaves a list thread", async () => {
    const { deps, recorded, staged } = postDeps(await weekReport(), null);
    const post = deps.post;
    deps.post = async (m) => (m.thread_ts ? { ok: false } : post(m));
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, true);
    assert.deepEqual(staged, []);
    assert.equal(recorded.length, 1);
    assert.equal(recorded[0]!.ts, "1759500000.000001");
    assert.equal(recorded[0]!.cardTs, "", "no card, but the thread is known");
  });

  it("keeps the report for tomorrow when the members cannot be read", async () => {
    const { deps, posts, reportBox } = postDeps(await weekReport(), null);
    deps.members = async () => null;
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, false);
    assert.deepEqual(posts, []);
    assert.notEqual(reportBox.box.value, null);
  });

  it("only a #plus-universal member can decide the card", async () => {
    const { deps, staged } = postDeps(await weekReport(), null);
    await postPrecedenceReport(deps);
    const threadState = createInMemoryThreadState();
    const card = staged[0]!;
    await threadState.putProposal(card);
    const react = (glyph: string, userId: string): GateSignal => ({
      kind: "reaction",
      messageTs: card.proposalTs,
      channel: CHANNEL,
      thread: card.replyTs!,
      glyph,
      userId,
    });
    const refused = await resolveSignal(react("white_check_mark", OUTSIDER), { threadState });
    assert.equal(refused.outcome, "none");
    assert.equal(refused.execute, undefined);
    const won = await resolveSignal(react("white_check_mark", MEMBERS[0]!), { threadState });
    assert.equal(won.outcome, "won");
    assert.deepEqual(won.execute!.operations.map((op) => op.toolName), ["github_issue_create"]);
  });

  it("a turn's card in the weekly thread leaves the weekly card live, and its ✅ still works", async () => {
    const { deps, staged } = postDeps(await weekReport(), null);
    await postPrecedenceReport(deps);
    const threadState = createInMemoryThreadState();
    const weekly = staged[0]!;
    await threadState.putProposal(weekly);
    // A turn answering an @mention in the same thread: it sees the weekly card
    // as the thread's pending card, but does not revise it.
    assert.equal(proposalSlot(weekly), `${weekly.replyTs}#ds-precedence`, "the weekly card holds its own slot");
    const agentCard: PendingProposal = {
      toolName: "notion_create",
      input: { title: "x" },
      channel: CHANNEL,
      threadTs: weekly.threadTs,
      replyTs: weekly.replyTs!,
      userMsgTs: "1759500009.000001",
      proposalTs: "1759500009.000002",
      proposalText: "card",
      requesterUserId: MEMBERS[0]!,
    };
    await threadState.putProposal(agentCard);
    assert.equal((await threadState.getProposalByTs(weekly.proposalTs)).state, "found");
    assert.equal((await threadState.getProposalByTs(agentCard.proposalTs)).state, "found");
    const won = await resolveSignal(
      { kind: "reaction", messageTs: weekly.proposalTs, channel: CHANNEL, thread: weekly.replyTs!, glyph: "white_check_mark", userId: MEMBERS[1]! },
      { threadState },
    );
    assert.equal(won.outcome, "won");
    assert.deepEqual(won.execute!.operations.map((op) => op.toolName), ["github_issue_create"]);
  });

  it("a ⛔ runs nothing: the card's one operation is the intake", async () => {
    const { deps, staged } = postDeps(await weekReport(), null);
    await postPrecedenceReport(deps);
    const threadState = createInMemoryThreadState();
    const card = staged[0]!;
    await threadState.putProposal(card);
    const verdict = await resolveSignal(
      { kind: "reaction", messageTs: card.proposalTs, channel: CHANNEL, thread: card.replyTs!, glyph: "no_entry", userId: MEMBERS[1]! },
      { threadState },
    );
    assert.equal(verdict.decision, "cancel");
    assert.equal(verdict.execute, undefined);
  });
});

describe("a dispute in the thread", () => {
  async function posted() {
    const { deps, staged, threadBox } = postDeps(await weekReport(), null);
    await postPrecedenceReport(deps);
    return { thread: threadBox.box.value!, first: staged[0]! };
  }

  it("reads `dispute N` replies, and nothing looser", () => {
    assert.deepEqual(disputedItems("dispute 2"), [2]);
    assert.deepEqual(disputedItems("dispute #1 and 3, see the set"), [1, 3]);
    assert.deepEqual(disputedItems("Dispute 2, 4"), [2, 4]);
    assert.deepEqual(disputedItems("<@UBOT> dispute 2 — it is on its way"), [2]);
    assert.deepEqual(disputedItems("item 2 looks wrong"), []);
    // Only a reply that STARTS with the word counts.
    assert.deepEqual(disputedItems("I wouldn't dispute 2"), []);
    assert.deepEqual(disputedItems("should we dispute 3?"), []);
    assert.deepEqual(disputedItems("dispute 3?"), [], "a question, not a dispute");
  });

  const NOW = Date.UTC(2026, 9, 5, 16, 0);

  /** The posted thread, its first card live in an in-memory ThreadState, and
   *  the dispute's dependencies over both. */
  async function world(opts: {
    postFails?: boolean;
    stageThrows?: boolean;
    writeThrows?: boolean;
    restoreThrows?: boolean;
    onPost?: (m: Post) => Promise<void>;
  } = {}) {
    const { thread, first } = await posted();
    const threadState = createInMemoryThreadState({ now: () => NOW });
    await threadState.putProposal(first);
    const record = kv<PostedThread | null>(thread);
    const posts: Post[] = [];
    const superseded: string[] = [];
    let n = 0;
    const deps: DisputeDeps = {
      thread: {
        read: record.store.read,
        write: async (v) => {
          if (opts.writeThrows) throw new Error("KV down");
          await record.store.write(v);
        },
      },
      post: async (m) => {
        posts.push(m);
        await opts.onPost?.(m);
        n += 1;
        return opts.postFails && m.blocks ? { ok: false } : { ok: true, ts: `175960000${n}.000001` };
      },
      stage: async (p) => {
        if (opts.stageThrows && p.proposalTs !== first.proposalTs) throw new Error("ThreadState down");
        await threadState.putProposal(p);
      },
      restore: async (p) => {
        if (opts.restoreThrows) throw new Error("ThreadState down");
        await threadState.putProposal(p);
      },
      retire: async (ts) => {
        await threadState.retireProposal(ts);
      },
      superseded: async (tss) => {
        superseded.push(...tss);
      },
      card: async (ts) => {
        const found = await threadState.getProposalByTs(ts);
        return found.state === "found" ? found.proposal : null;
      },
      now: () => NOW,
    };
    const dispute = (text: string, threadTs = thread.ts) =>
      disputePrecedenceItems(deps, { channel: CHANNEL, threadTs, user: MEMBERS[0]!, text });
    return { thread, first, threadState, record, posts, deps, dispute, superseded };
  }

  it("revises the card without the disputed item, in the same thread", async () => {
    const w = await world();
    assert.equal(await w.dispute("dispute 2 — TreeSelect is on its way"), true);
    assert.equal(w.posts.length, 1);
    assert.equal(w.posts[0]!.thread_ts, w.thread.ts);
    const revised = await w.threadState.getProposalByTs(w.record.box.value!.cardTs);
    assert.equal(revised.state, "found");
    const p = revised.state === "found" ? revised.proposal : null;
    assert.equal(p!.supersedeKey, w.first.supersedeKey, "the revision shares the weekly card's key");
    assert.deepEqual(p!.confirmers, MEMBERS);
    const body = String(p!.operations![0]!.input.body);
    assert.match(body, /Button/);
    assert.doesNotMatch(body, /TreeSelect/);
    assert.ok((p!.ttlMs ?? 0) < PRECEDENCE_CARD_TTL_MS, "a revision does not extend the card's life");
    assert.deepEqual(w.record.box.value?.disputed, [2]);
    assert.equal((await w.threadState.getProposalByTs(w.first.proposalTs)).state, "superseded");
    assert.deepEqual(w.superseded, [w.first.proposalTs], "superseded on the usage record once the revision is in place");
  });

  it("disputing every item withdraws the card", async () => {
    const w = await world();
    assert.equal(await w.dispute("dispute 1, 2"), true);
    assert.equal((await w.threadState.getProposalByTs(w.first.proposalTs)).state, "superseded");
    assert.match(w.posts[0]!.text, /withdrawn/);
  });

  it("the old card is retired before the revision posts, so a racing ✅ runs nothing", async () => {
    const outcomes: string[] = [];
    const w = await world({
      onPost: async (m) => {
        if (!m.blocks) return;
        const verdict = await resolveSignal(
          { kind: "reaction", messageTs: w.first.proposalTs, channel: CHANNEL, thread: w.thread.ts, glyph: "white_check_mark", userId: MEMBERS[1]! },
          { threadState: w.threadState },
        );
        outcomes.push(verdict.outcome);
      },
    });
    await w.dispute("dispute 2");
    assert.equal(outcomes.length, 1);
    assert.notEqual(outcomes[0], "won", "a confirm on the retired card resolves nothing");
  });

  it("a revision that fails to post restores the old card", async () => {
    const w = await world({ postFails: true });
    assert.equal(await w.dispute("dispute 2"), true);
    assert.equal((await w.threadState.getProposalByTs(w.first.proposalTs)).state, "found");
    assert.equal(w.record.box.value?.cardTs, w.first.proposalTs);
    assert.deepEqual(w.record.box.value?.disputed, []);
  });

  it("a revision that posts but does not stage restores the old card and says so, and later disputes still work", async () => {
    const w = await world({ stageThrows: true });
    assert.equal(await w.dispute("dispute 2"), true, "no fall-through to a turn");
    assert.equal((await w.threadState.getProposalByTs(w.first.proposalTs)).state, "found");
    assert.equal(w.record.box.value?.cardTs, w.first.proposalTs, "the record names the live card");
    assert.deepEqual(w.superseded, [], "the restored card is not superseded on the record");
    assert.match(w.posts.at(-1)!.text, /didn't go through/);
    // The next dispute is judged against the card that is actually live.
    const posted = w.posts.length;
    assert.equal(await w.dispute("dispute 9"), true);
    assert.match(w.posts[posted]!.text, /not on this week's list/);
  });

  it("a revision whose record does not write restores the old card over it", async () => {
    const w = await world({ writeThrows: true });
    assert.equal(await w.dispute("dispute 2"), true);
    assert.equal((await w.threadState.getProposalByTs(w.first.proposalTs)).state, "found");
    const revisionTs = w.posts.find((m) => m.blocks) ? "1759600001.000001" : "";
    assert.notEqual((await w.threadState.getProposalByTs(revisionTs)).state, "found", "the revision is not live");
    assert.match(w.posts.at(-1)!.text, /didn't go through/);
  });

  it("a revision that fails and whose old card cannot be put back says neither went through", async () => {
    const w = await world({ stageThrows: true, restoreThrows: true });
    assert.equal(await w.dispute("dispute 2"), true);
    const last = w.posts.at(-1)!.text;
    assert.match(last, /didn't go through/);
    assert.doesNotMatch(last, /still stands/, "the old card is not live, so the reply does not say it is");
  });

  it("a card re-staged after a cut-off is followed by the record, so a later dispute revises it", async () => {
    const w = await world();
    // What a cut-off re-stage does: a fresh card, the old one's terms, rooted
    // at it (`restageExecution`).
    const restaged: PendingProposal = { ...w.first, proposalTs: "1759600500.000001", originProposalTs: w.first.proposalTs };
    await w.threadState.putProposal(restaged);
    await followRestagedCard(w.deps.thread, w.first, restaged);
    assert.equal(w.record.box.value?.cardTs, restaged.proposalTs);

    assert.equal(await w.dispute("dispute 2"), true);
    assert.ok(w.posts[0]!.blocks, "a revised card, not \"already decided or expired\"");
    assert.equal((await w.threadState.getProposalByTs(restaged.proposalTs)).state, "superseded");
  });

  it("a re-staged card that is not the thread's live one moves nothing", async () => {
    const w = await world();
    const other: PendingProposal = { ...w.first, proposalTs: "1.1" };
    await followRestagedCard(w.deps.thread, other, { ...other, proposalTs: "1.2" });
    assert.equal(w.record.box.value?.cardTs, w.first.proposalTs);
  });

  it("a dispute that changes nothing says why in one line", async () => {
    const w = await world();
    await w.dispute("dispute 9");
    assert.match(w.posts.at(-1)!.text, /^Item 9 is not on this week's list\.$/);
    await w.dispute("dispute 2");
    await w.dispute("dispute 2");
    assert.match(w.posts.at(-1)!.text, /^Item 2 is already dropped\.$/);
    assert.deepEqual(w.record.box.value?.disputed, [2]);
  });

  it("a dispute after the card is decided revises nothing, so no second intake is filed", async () => {
    const w = await world();
    const won = await resolveSignal(
      { kind: "reaction", messageTs: w.first.proposalTs, channel: CHANNEL, thread: w.thread.ts, glyph: "white_check_mark", userId: MEMBERS[0]! },
      { threadState: w.threadState },
    );
    assert.equal(won.outcome, "won");
    assert.equal(await w.dispute("dispute 2"), true);
    assert.equal(w.posts.length, 1);
    assert.match(w.posts[0]!.text, /already been decided or has expired/);
    assert.equal(w.posts[0]!.blocks, undefined, "no revised card");
  });

  it("leaves a reply outside a list thread, or one that is no dispute, to the ordinary path", async () => {
    const w = await world();
    assert.equal(await w.dispute("thanks!"), false);
    assert.equal(await w.dispute("dispute 1", "1.2"), false);
    assert.deepEqual(w.posts, []);
  });

  it("the operations a card runs follow the target", () => {
    const items = [{ n: 1, component: "Button", summary: "s", codeUrl: "c", figmaUrl: "f", loser: "library" }] as never;
    assert.equal(precedenceOperations(items, { kind: "create" }, "2026-10-02")[0]!.toolName, "github_issue_create");
    assert.equal(
      precedenceOperations(items, { kind: "update", issue: 7, url: "u" }, "2026-10-02")[0]!.toolName,
      "github_issue_update",
    );
  });
});

describe("the Slack hook", () => {
  const thread = {
    channel: CHANNEL,
    ts: "1759500000.000001",
    items: [{ n: 1 }, { n: 2 }],
    disputed: [2],
    expiresAt: Date.now() + PRECEDENCE_CARD_TTL_MS,
  } as unknown as PostedThread;
  const env = (reads: string[], cardState = "found") =>
    ({
      PLUS_UNIVERSAL_CHANNEL_ID: CHANNEL,
      // The ThreadState namespace, as far as the card lookup reaches it.
      THREAD_STATE: {
        idFromName: (name: string) => name,
        get: () => ({ getProposalByTs: async () => ({ state: cardState }) }),
      },
      HARNESS_KV: {
        get: async (key: string) => {
          reads.push(key);
          return thread;
        },
      },
    }) as unknown as Env;
  const msg = (over: Partial<SlackMessageEvent>): SlackMessageEvent =>
    ({ type: "message", channel: CHANNEL, thread_ts: thread.ts, ts: "1759500001.000001", user: "U1", text: "dispute 1", ...over }) as SlackMessageEvent;

  it("reads nothing for a message that cannot be a dispute", async () => {
    const reads: string[] = [];
    assert.equal(await handleDsPrecedenceReply(env(reads), msg({ text: "looks right to me" })), false);
    assert.equal(await handleDsPrecedenceReply(env(reads), msg({ channel: "C0OTHER" })), false);
    assert.equal(await handleDsPrecedenceReply(env(reads), msg({ thread_ts: undefined })), false);
    assert.deepEqual(reads, []);
  });

  it("queues a person's `dispute N` reply or broadcast in a #plus-universal thread, and nothing else", () => {
    const e = env([]);
    assert.equal(isDsPrecedenceCandidate(e, msg({})), true);
    assert.equal(isDsPrecedenceCandidate(e, msg({ text: "<@UBOT> dispute 1" })), true);
    assert.equal(isDsPrecedenceCandidate(e, msg({ subtype: "thread_broadcast" })), true);
    assert.equal(isDsPrecedenceCandidate(e, msg({ subtype: "message_changed" })), false);
    assert.equal(isDsPrecedenceCandidate(e, msg({ bot_id: "B1" })), false);
    assert.equal(isDsPrecedenceCandidate(e, msg({ channel: "C0OTHER" })), false);
    assert.equal(isDsPrecedenceCandidate(e, msg({ thread_ts: undefined })), false);
    assert.equal(isDsPrecedenceCandidate(e, msg({ text: "I wouldn't dispute 1" })), false);
  });

  it("a cut-off re-stage of the weekly card moves its thread's record; any other card reads nothing", async () => {
    const reads: string[] = [];
    const puts: Array<[string, PostedThread]> = [];
    const e = {
      HARNESS_KV: {
        get: async (key: string) => {
          reads.push(key);
          return { ...thread, cardTs: "1759500000.000002" };
        },
        put: async (key: string, value: string) => {
          puts.push([key, JSON.parse(value) as PostedThread]);
        },
      },
    } as unknown as Env;
    const from = { supersedeKey: "ds-precedence", proposalTs: "1759500000.000002", replyTs: thread.ts, threadTs: thread.ts } as PendingProposal;
    await recordPrecedenceRestageFor(e, from, { ...from, proposalTs: "1759500900.000001" });
    assert.equal(puts.length, 1);
    assert.match(puts[0]![0], new RegExp(thread.ts.replace(".", "\\.")));
    assert.equal(puts[0]![1].cardTs, "1759500900.000001");

    reads.length = 0;
    await recordPrecedenceRestageFor(e, { ...from, supersedeKey: "sweep" }, { ...from, proposalTs: "2.2" });
    assert.deepEqual(reads, []);
  });

  it("knows the weekly thread, so its replies are not all turns", async () => {
    assert.equal(await isWeeklyPrecedenceThread(env([]), CHANNEL, thread.ts), true);
    assert.equal(await isWeeklyPrecedenceThread(env([]), CHANNEL, "1.1"), false);
    const reads: string[] = [];
    assert.equal(await isWeeklyPrecedenceThread(env(reads), "C0OTHER", thread.ts), false);
    assert.deepEqual(reads, [], "another channel reads nothing");
  });
});
