// The weekly DS precedence check, end to end on fakes: the end-of-day check
// compares the component index and the registry's props with the Figma
// library, the next morning run posts one report of shared decision cards in
// #plus-universal — one card per component — and each card's Approve adds its
// component to the week's one intake, filing it on the first.
//
// The fixtures are drawn from the manual first pass of this check (#339): the
// five button sets that split what code keeps as one `fill` prop, a code
// component with no Figma set, and a component on which both sides agree.
import { describe, it } from "node:test";
import assert from "node:assert/strict";

import type { FigmaComponentsResponse } from "../src/figma/client";
import { createInMemoryFigma } from "../src/figma/in-memory";
import {
  findDisagreements,
  inFlightComponents,
  liveLibraryFrom,
  losingSide,
  parseComponentIndex,
  type PrecedenceRegistry,
} from "../src/ds-precedence/compare";
import { PRECEDENCE_INTAKE_TOOL, precedenceMarker, precedenceRuleUrl } from "../src/ds-precedence/report";
import { addToWeeklyIntake, type IntakeDeps } from "../src/ds-precedence/intake";
import { disputePrecedenceItem } from "../src/ds-precedence/dispute";
import {
  NOT_STAGED,
  postPrecedenceReport,
  precedenceChannel,
  runPrecedenceCheck,
  PRECEDENCE_CARD_TTL_MS,
  type CheckDeps,
  type PostedThread,
  type PostDeps,
  type PrecedenceReport,
} from "../src/ds-precedence/jobs";
import { isWeeklyPrecedenceThread } from "../src/ds-precedence/env";
import { TOOL_TABLE } from "../src/agent/tool-table";
import type { Env } from "../src/types";
import { messageBlocksRefusal } from "./helpers/slack-block-rules";
import { recordingViews } from "./helpers/recording-slack";
import type { OperationOutcome } from "../src/gate/run-batch";
import { itemProposal } from "../src/slack/decision-cards";
import { runReviewDecision, type ReviewDoorDeps } from "../src/slack/review-door";
import type { CardMessage } from "../src/slack/button-door";
import { recordingDelivery } from "../src/turn/index";
import { createInMemoryThreadState, type PendingProposal, type ThreadState } from "../src/thread-state/index";

const FILE_KEY = "zAecJNRdvJzAUOcjV32tRX";
const REPO = "BilLogic/plus-uno";
const CHANNEL = "C072E8SFLKV";
const MEMBERS = ["U0MEMBER1", "U0MEMBER2"];

// ── Fixtures (#339) ──────────────────────────────────────────────────────────

const INDEX_MD = `<!-- DO NOT EDIT BY HAND. Generated by npm run generate:agent -->
# PLUS DS — Components

## UI components (4)

- [Button](../../src/components/actions/Button/index.md)
- [Tooltip](../../src/components/overlays/Tooltip/index.md)
- [TreeSelect](../../src/components/forms-and-inputs/TreeSelect.md)
- [Scale](../../src/components/forms-and-inputs/RadioButtonGroup.md) — alias of \`RadioButtonGroup\`, same props
`;

const variant = (name: string, node: string, set: string, setNode: string) => ({
  key: `k-${node}`,
  name,
  node_id: node,
  containing_frame: { name: "Buttons", nodeId: "1:1", containingComponentSet: { name: set, nodeId: setNode } },
});

const buttonSet = (set: string, setNode: string, n: number) => [
  variant("size=small, style=primary, state=rest (default)", `${n}:1`, set, setNode),
  variant("size=medium (default), style=secondary, state=hover", `${n}:2`, set, setNode),
  variant("size=large, style=primary, state=rest (default)", `${n}:3`, set, setNode),
];

/** The library: four fill sets for the one Button, a Tooltip that agrees, an
 *  internal part, and no TreeSelect at all. */
const LIBRARY: FigmaComponentsResponse = {
  meta: {
    components: [
      ...buttonSet("Filled buttons", "33:2470", 100),
      ...buttonSet("Tonal buttons", "979:20977", 200),
      ...buttonSet("Outlined buttons", "33:2471", 300),
      ...buttonSet("Text buttons", "33:2472", 400),
      variant("placement=top", "500:1", "Tooltip", "300:1"),
      variant("placement=bottom", "500:2", "Tooltip", "300:1"),
      variant("depth=0", "600:1", "_tree_select", "600:9"),
    ],
  },
};

const set = (name: string, node: string, fill: string) => ({
  name,
  componentSetNodeId: node,
  codeDefaults: { fill },
  variantProps: { size: "size", style: "style", state: "state" },
  variantValueMap: { size: { small: "small", "medium (default)": "medium", large: "large" } },
  status: "verified",
});

const REGISTRY: PrecedenceRegistry = {
  components: {
    Button: {
      code: {
        mdxPath: "design-system/src/components/actions/Button/Button.mdx",
        props: {
          style: { type: "enum", values: ["primary", "secondary"] },
          fill: { type: "enum", values: ["filled", "tonal", "outline", "ghost", "text"] },
          size: { type: "enum", values: ["small", "medium", "large"] },
          disabled: { type: "boolean" },
        },
      },
      figma: {
        sets: [
          { name: "Buttons docs page (MDX link)", componentSetNodeId: "3497:19482", status: "docs-page", isComponentSet: false },
          set("Filled buttons", "33:2470", "filled"),
          set("Tonal buttons", "979:20977", "tonal"),
          set("Outlined buttons", "33:2471", "outline"),
          set("Text buttons", "33:2472", "text"),
        ],
      },
    },
    Tooltip: {
      code: {
        mdxPath: "design-system/src/components/overlays/Tooltip/Tooltip.mdx",
        props: { placement: { type: "enum", values: ["top", "bottom"] } },
      },
      figma: { sets: [{ name: "Tooltip", componentSetNodeId: "300:1", status: "verified" }] },
    },
    TreeSelect: {
      code: { mdxPath: "design-system/src/components/forms-and-inputs/TreeSelect.mdx" },
      figma: { sets: [{ name: "_tree_select", componentSetNodeId: "600:9", status: "unpublished", isComponentSet: false }] },
    },
  },
};

function check(inFlight: ReadonlySet<string> = new Set()) {
  return findDisagreements({
    index: parseComponentIndex(INDEX_MD),
    registry: REGISTRY,
    library: liveLibraryFrom(LIBRARY),
    fileKey: FILE_KEY,
    repo: REPO,
    inFlight,
  });
}

// ── The comparison ───────────────────────────────────────────────────────────

describe("the comparison", () => {
  it("the rule decides the loser: code, then the BS4 library, then the spec pages", () => {
    assert.equal(losingSide("code", "library"), "library");
    assert.equal(losingSide("spec-pages", "library"), "spec-pages");
    assert.equal(losingSide("code", "spec-pages"), "spec-pages");
  });

  it("reads the index as the existence list, aliases left out", () => {
    assert.deepEqual(
      parseComponentIndex(INDEX_MD).map((e) => [e.name, e.docPath]),
      [
        ["Button", "design-system/src/components/actions/Button/index.md"],
        ["Tooltip", "design-system/src/components/overlays/Tooltip/index.md"],
        ["TreeSelect", "design-system/src/components/forms-and-inputs/TreeSelect.md"],
      ],
    );
  });

  it("reports Button's fill-as-sets against fill-as-prop, with Figma losing", () => {
    const button = check().filter((d) => d.component === "Button");
    assert.equal(button.length, 1, JSON.stringify(button));
    const [d] = button;
    assert.equal(d!.kind, "prop-as-sets");
    assert.equal(d!.loser, "library");
    assert.equal(d!.winner, "code");
    // #886's register, without the component's name: the item line leads with it.
    assert.match(d!.summary, /^code has one `fill` prop \(/);
    assert.match(d!.summary, /, the library splits it into \d+ components: .*Filled buttons/);
    assert.match(d!.summary, /; `ghost` has no component$/);
    assert.equal(d!.codeUrl, `https://github.com/${REPO}/blob/main/design-system/src/components/actions/Button/index.md`);
    assert.match(d!.figmaUrl, /node-id=33-2470/);
  });

  it("reports a component in code that the library does not have", () => {
    const tree = check().filter((d) => d.component === "TreeSelect");
    assert.equal(tree.length, 1);
    assert.equal(tree[0]!.kind, "missing-in-figma");
    assert.equal(tree[0]!.summary, "code has it, the library has no published component for it");
    assert.equal(tree[0]!.loser, "library");
    assert.equal(tree[0]!.figmaUrl, `https://www.figma.com/design/${FILE_KEY}`);
  });

  it("does not report a component on which both sides agree", () => {
    assert.deepEqual(check().filter((d) => d.component === "Tooltip"), []);
  });

  it("reports values an axis lacks, after the registry's value map", () => {
    const registry = structuredClone(REGISTRY);
    registry.components.Tooltip!.code!.props = { placement: { type: "enum", values: ["top", "bottom", "start"] } };
    const found = findDisagreements({
      index: parseComponentIndex(INDEX_MD),
      registry,
      library: liveLibraryFrom(LIBRARY),
      fileKey: FILE_KEY,
      repo: REPO,
      inFlight: new Set(),
    }).filter((d) => d.component === "Tooltip");
    assert.equal(found.length, 1);
    assert.equal(found[0]!.kind, "axis-values");
    assert.equal(found[0]!.summary, 'code has `placement="start"`, the library doesn\'t');
    // Button's `size` maps "medium (default)" to medium, so it is not reported.
    assert.equal(check().some((d) => d.component === "Button" && d.kind === "axis-values"), false);
  });

  it("leaves out a component a library publish is still carrying, where code follows", () => {
    const inFlight = inFlightComponents(
      [{ implement: "Button, Tooltip" }],
      [
        {
          created: [],
          modified: [{ key: "k", name: "placement=top", description: "", nodeId: "500:1", containingFrame: "Tooltip", setNodeId: "300:1" }],
          deleted: [],
        },
      ],
      REGISTRY,
    );
    assert.deepEqual([...inFlight].sort(), ["Button", "Tooltip"]);
    assert.deepEqual(check(inFlight).map((d) => d.component), ["TreeSelect"]);
  });
});

// ── The jobs ─────────────────────────────────────────────────────────────────

function kv<T>(initial: T) {
  const box = { value: initial, writes: 0 };
  return {
    box,
    store: {
      read: async () => box.value,
      write: async (v: T) => {
        box.value = v;
        box.writes += 1;
      },
    },
  };
}

function checkDeps(library: FigmaComponentsResponse, report = kv<PrecedenceReport | null>(null)) {
  const figma = createInMemoryFigma();
  figma.seedFile(FILE_KEY, { components: library });
  const deps: CheckDeps = {
    github: { indexMarkdown: async () => INDEX_MD, registry: async () => REGISTRY },
    figma,
    report: report.store,
    inFlight: async () => new Set<string>(),
    fileKey: FILE_KEY,
    repo: REPO,
    now: () => Date.UTC(2026, 9, 2, 22, 0),
    runDate: "2026-10-02",
  };
  return { deps, report };
}

/** A library on which every component agrees: Button as one set with a fill
 *  axis, and TreeSelect present. */
const AGREEING: FigmaComponentsResponse = {
  meta: {
    components: [
      variant("size=small, style=primary, fill=filled", "1:1", "Button", "9:1"),
      variant("size=medium, style=secondary, fill=tonal", "1:2", "Button", "9:1"),
      variant("size=large, style=primary, fill=outline", "1:3", "Button", "9:1"),
      variant("size=large, style=primary, fill=ghost", "1:4", "Button", "9:1"),
      variant("size=large, style=primary, fill=text", "1:5", "Button", "9:1"),
      variant("placement=top", "500:1", "Tooltip", "300:1"),
      variant("placement=bottom", "500:2", "Tooltip", "300:1"),
      variant("depth=0", "600:1", "Tree Select", "600:10"),
    ],
  },
};

interface Post {
  text: string;
  blocks?: unknown[];
}

/** The report's message ts, and a clock ten minutes after it. */
const MSG = "1759500000.000001";
const NOW = Number(MSG) * 1000 + 10 * 60_000;

function postDeps(report: PrecedenceReport | null, store: ThreadState = createInMemoryThreadState({ now: () => NOW })) {
  const posts: Post[] = [];
  const edits: Array<{ ts: string; message: Post }> = [];
  const staged: PendingProposal[] = [];
  const reportBox = kv<PrecedenceReport | null>(report);
  const recorded: PostedThread[] = [];
  let n = 0;
  const deps: PostDeps = {
    report: reportBox.store,
    recordThread: async (thread) => void recorded.push(thread),
    members: async () => [...MEMBERS],
    post: async (message) => {
      posts.push(message);
      n += 1;
      return { ok: true, ts: `1759500000.00000${n}` };
    },
    edit: async (ts, message) => void edits.push({ ts, message }),
    reports: store,
    stage: async (proposal) => {
      staged.push(proposal);
      await store.putProposal(proposal);
    },
    channel: CHANNEL,
    ruleUrl: precedenceRuleUrl(REPO),
    now: () => NOW,
  };
  return { deps, posts, edits, staged, reportBox, recorded, store };
}

describe("the end-of-day check", () => {
  it("keeps the disagreements for the morning", async () => {
    const { deps, report } = checkDeps(LIBRARY);
    const result = await runPrecedenceCheck(deps);
    assert.equal(result.found, 2);
    assert.deepEqual(report.box.value?.items.map((i) => i.component), ["Button", "TreeSelect"]);
  });

  it("a clean week keeps nothing, and clears a report nobody posted", async () => {
    const stale = kv<PrecedenceReport | null>({ checkedAt: "x", items: [] as PrecedenceReport["items"] } as PrecedenceReport);
    const { deps, report } = checkDeps(AGREEING, stale);
    const result = await runPrecedenceCheck(deps);
    assert.equal(result.found, 0);
    assert.equal(report.box.value, null);
  });

  it("an empty or near-empty library skips the week rather than reporting every component missing", async () => {
    // Nothing at all; one indexed component of three; and a library padded
    // with sets the index does not list (icons), which count for nothing.
    const icons = Array.from({ length: 40 }, (_, i) => variant(`size=${i}`, `9${i}:1`, `Icon ${i}`, `9${i}:9`));
    for (const components of [[], LIBRARY.meta!.components!.slice(0, 1), icons]) {
      const waiting = { checkedAt: "2026-09-25T22:00:00.000Z", items: [] } as unknown as PrecedenceReport;
      const stale = kv<PrecedenceReport | null>(waiting);
      const { deps, report } = checkDeps({ meta: { components } }, stale);
      const result = await runPrecedenceCheck(deps);
      assert.equal(result.found, 0);
      assert.match(result.summary, /week skipped/);
      assert.equal(report.box.writes, 0, "a report still waiting for its morning is left as it is");
      assert.equal(report.box.value, waiting);
    }
  });

  it("a dry run compares and writes nothing", async () => {
    const { deps, report } = checkDeps(LIBRARY);
    await runPrecedenceCheck(deps, { dryRun: true });
    assert.equal(report.box.writes, 0);
  });

  it("under EST, Friday's check runs on Saturday and labels the week with Friday, its run's date", async () => {
    // Friday 2026-12-04 is swept at Saturday 00:00 EST, 05:00 UTC, and the
    // check, deferred on a budget stop, runs at 05:10 UTC.
    const { deps, report } = checkDeps(LIBRARY);
    await runPrecedenceCheck({ ...deps, now: () => Date.UTC(2026, 11, 5, 5, 10), runDate: "2026-12-04" });
    const morning = postDeps(report.box.value);
    await postPrecedenceReport(morning.deps);
    assert.equal(morning.recorded[0]!.weekOf, "2026-12-04");
    assert.equal(morning.staged[0]!.operations![0]!.input.week_of, "2026-12-04");
    assert.match(morning.staged[0]!.proposalText, /week of Dec 4/);
  });

  it("a report kept before the run's date was recorded is labelled with its check's date", async () => {
    const kept = { checkedAt: "2026-09-25T22:00:00.000Z", items: (await weekReport()).items };
    const morning = postDeps(kept);
    await postPrecedenceReport(morning.deps);
    assert.equal(morning.staged[0]!.operations![0]!.input.week_of, "2026-09-25");
  });
});

async function weekReport(): Promise<PrecedenceReport> {
  const { deps, report } = checkDeps(LIBRARY);
  await runPrecedenceCheck(deps);
  return report.box.value!;
}

type Card = {
  title: { text: string };
  subtitle?: { text: string };
  body: { text: string };
  actions: Array<{ text: { text: string }; action_id?: string; url?: string }>;
};
/** The cards of a report message: a carousel's, or its one card. */
function cardsIn(blocks: unknown[]): Card[] {
  const second = blocks[1] as { type: string; elements?: Card[] } & Card;
  return second.type === "carousel" ? second.elements! : [second];
}

/** No typed gate copy: nothing to react, type, drop or skip. */
const GATE_WORDS = /:white_check_mark:|:no_entry:|✅|⛔|\bdrop\b|\bskip\b|\bdispute\b|[Rr]eply\b/;

/** A report of `n` disagreements, one component each. */
const reportOf = (n: number): PrecedenceReport => ({
  checkedAt: "2026-10-02T22:00:00.000Z",
  weekOf: "2026-10-02",
  items: Array.from({ length: n }, (_, i) => ({
    key: `Component${i + 1}:missing`,
    component: `Component${i + 1}`,
    kind: "missing-in-figma" as const,
    summary: "code has it, the library has no published component for it",
    codeUrl: `https://github.com/${REPO}/blob/main/Component${i + 1}.md`,
    figmaUrl: `https://www.figma.com/design/KEY?node-id=1-${i + 1}`,
    winner: "code" as const,
    loser: "library" as const,
  })),
});

describe("the morning post", () => {
  it("lands where pickDestination sends a design-system finding: #plus-universal, never #plus-design", () => {
    assert.equal(precedenceChannel({ plusUniversal: CHANNEL, plusDesign: "C0DESIGN" }), CHANNEL);
    assert.equal(precedenceChannel({ plusDesign: "C0DESIGN" }), null, "no fallback to another channel");
  });

  it("a clean week posts nothing", async () => {
    const { deps, posts, staged } = postDeps(null);
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, false);
    assert.deepEqual(posts, []);
    assert.deepEqual(staged, []);
  });

  it("posts one message: a plain parent line, then one card per component with Review, Code and Figma", async () => {
    const { deps, posts, reportBox, recorded } = postDeps(await weekReport());
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, true);
    assert.equal(posts.length, 1, "one message, nothing in a thread");
    const [message] = posts;
    assert.equal(messageBlocksRefusal(message!.blocks!), null);
    assert.match(
      JSON.stringify(message!.blocks![0]),
      new RegExp(
        `Code and the library disagree on 2 components\\. <https://github\\.com/${REPO}/blob/main/AGENTS\\.md#conventions--what-agents-obey\\|Code wins> unless a difference is deliberate\\.`,
      ),
    );
    const [button, tree] = cardsIn(message!.blocks!);
    assert.equal(button!.title.text, "Button");
    assert.equal(button!.subtitle!.text, "Library side");
    assert.match(button!.body.text, /^Code has one fill prop \(/, "plain words, no backticks");
    assert.deepEqual(button!.actions.map((a) => a.text.text), ["Review", "Code", "Figma"]);
    assert.match(button!.actions[1]!.url!, /^https:\/\/github\.com\/BilLogic\/plus-uno\/blob\/main\//);
    assert.match(button!.actions[2]!.url!, /^https:\/\/www\.figma\.com\//);
    assert.equal(tree!.title.text, "TreeSelect");
    assert.equal(tree!.body.text, "Code has it, the library has no published component for it.");
    assert.doesNotMatch(JSON.stringify(message), GATE_WORDS);

    assert.equal(reportBox.box.value, null, "the report is handed off");
    assert.deepEqual(recorded, [{ channel: CHANNEL, ts: MSG, weekOf: "2026-10-02" }]);
  });

  it("stages each component as its own proposal: the week's intake, decided by the channel's members, for six days", async () => {
    const { deps, staged } = postDeps(await weekReport());
    await postPrecedenceReport(deps);
    assert.equal(staged.length, 2, "one proposal per card");
    const [button, tree] = staged;
    assert.equal(button!.proposalTs, itemProposal(MSG, "Button").proposalTs);
    assert.deepEqual(button!.item, { messageTs: MSG, id: "Button" });
    assert.notEqual(button!.supersedeKey, tree!.supersedeKey, "each card its own slot");
    assert.deepEqual(button!.confirmers, MEMBERS);
    assert.equal(button!.ttlMs, PRECEDENCE_CARD_TTL_MS);
    assert.equal(button!.onCancel, undefined, "a Reject runs nothing");
    assert.deepEqual(button!.operations!.map((o) => o.toolName), [PRECEDENCE_INTAKE_TOOL]);
    assert.equal(button!.operations![0]!.input.week_of, "2026-10-02");
    assert.match(String(button!.operations![0]!.input.section), /^### Button\n/);
    assert.doesNotMatch(String(button!.operations![0]!.input.section), /TreeSelect/, "only its own component");
    assert.match(button!.proposalText, /Button/);
    assert.match(button!.proposalText, /intake for the week of Oct 2/);
    assert.deepEqual(button!.stated, {
      cancelled: "Left as deliberate, nothing filed",
      expired: "That card closed after 6 days with no decision, so nothing was filed.",
    });
    for (const p of staged) assert.doesNotMatch(`${p.proposalText} ${p.refuseRevision}`, GATE_WORDS);
  });

  it("several disagreements on one component are one card", async () => {
    const two = reportOf(1);
    two.items.push({ ...two.items[0]!, key: "Component1:size:axis-values", kind: "axis-values", summary: "code has `size=\"xs\"`, the library doesn't" });
    const { deps, posts, staged } = postDeps(two);
    await postPrecedenceReport(deps);
    const cards = cardsIn(posts[0]!.blocks!);
    assert.equal(cards.length, 1);
    assert.equal(cards[0]!.body.text, 'Code has it, the library has no published component for it; code has size="xs", the library doesn\'t.');
    assert.equal(staged.length, 1);
    assert.match(String(staged[0]!.operations![0]!.input.section), /xs/);
  });

  it("shows ten cards and keeps the rest for tomorrow's report, under the same week", async () => {
    const { deps, posts, staged, reportBox } = postDeps(reportOf(12));
    await postPrecedenceReport(deps);
    assert.equal(cardsIn(posts[0]!.blocks!).length, 10);
    assert.match(JSON.stringify(posts[0]!.blocks![0]), /disagree on 12 components\..*Showing 10 of 12; the rest come in the next report\./);
    assert.equal(staged.length, 10);
    assert.deepEqual(reportBox.box.value?.items.map((i) => i.component), ["Component11", "Component12"]);
    assert.equal(reportBox.box.value?.weekOf, "2026-10-02");

    const tomorrow = postDeps(reportBox.box.value);
    await postPrecedenceReport(tomorrow.deps);
    assert.equal(cardsIn(tomorrow.posts[0]!.blocks!).length, 2);
    assert.equal(tomorrow.staged[0]!.operations![0]!.input.week_of, "2026-10-02");
    assert.equal(tomorrow.reportBox.box.value, null);
  });

  it("a card that does not stage says so with nothing to review, and posts again tomorrow", async () => {
    const { deps, edits, reportBox } = postDeps(await weekReport());
    const stage = deps.stage;
    deps.stage = async (p) => (p.item?.id === "TreeSelect" ? Promise.reject(new Error("DO down")) : stage(p));
    const result = await postPrecedenceReport(deps);
    assert.equal(result.posted, true);
    assert.equal(edits.length, 1);
    assert.equal(edits[0]!.ts, MSG);
    const [, tree] = cardsIn(edits[0]!.message.blocks!);
    assert.equal(tree!.subtitle!.text, NOT_STAGED);
    assert.deepEqual(tree!.actions.map((a) => a.text.text), ["Code", "Figma"], "no Review");
    assert.deepEqual(reportBox.box.value?.items.map((i) => i.component), ["TreeSelect"]);
  });

  it("keeps the report for tomorrow when the members cannot be read, or the message does not post", async () => {
    const unread = postDeps(await weekReport());
    unread.deps.members = async () => null;
    assert.equal((await postPrecedenceReport(unread.deps)).posted, false);
    assert.deepEqual(unread.posts, []);
    assert.notEqual(unread.reportBox.box.value, null);

    const refused = postDeps(await weekReport());
    refused.deps.post = async () => ({ ok: false });
    assert.equal((await postPrecedenceReport(refused.deps)).posted, false);
    assert.deepEqual(refused.staged, []);
    assert.notEqual(refused.reportBox.box.value, null);
  });

  it("a dry run drafts and posts, stages and writes nothing", async () => {
    const { deps, posts, staged, reportBox } = postDeps(await weekReport());
    const result = await postPrecedenceReport(deps, { dryRun: true });
    assert.equal(result.posted, false);
    assert.match(result.summary, /would post 2 component card/);
    assert.deepEqual(posts, []);
    assert.deepEqual(staged, []);
    assert.equal(reportBox.box.writes, 0);
  });
});

// ── The week's intake ────────────────────────────────────────────────────────

type Issue = { number: number; url: string; body: string };

/** A harness repo — every intake updated this week, open or closed — the
 *  week's filing on a ThreadState, and every write made. */
function github(issues: Issue[] = [], store: ThreadState = createInMemoryThreadState({ now: () => NOW })) {
  const created: Array<{ title: string; body: string }> = [];
  const comments: Array<{ issue_number: number; comment: string }> = [];
  const lookups = { count: 0 };
  const deps: IntakeDeps = {
    filing: { claim: (key) => store.claimFiling(key), settle: (key, issue) => store.settleFiling(key, issue) },
    async intakesSince() {
      lookups.count += 1;
      return { intakes: [...issues], complete: true };
    },
    async create(input) {
      // A real round trip: the other Approve runs meanwhile.
      await new Promise((resolve) => setTimeout(resolve, 5));
      created.push(input);
      const number = 1100 + created.length;
      issues.push({ number, url: `https://github.com/${REPO}/issues/${number}`, body: input.body });
      return JSON.stringify({ ok: true, issue_number: number, issue_url: `https://github.com/${REPO}/issues/${number}` });
    },
    async comment(input) {
      comments.push(input);
      return JSON.stringify({ ok: true });
    },
    sleep: (ms) => new Promise((resolve) => setTimeout(resolve, Math.min(ms, 2))),
  };
  return { deps, created, comments, lookups, store };
}

const section = (component: string) => ({ week_of: "2026-10-02", component, section: `### ${component}\n\n| … |` });

describe("the week's intake", () => {
  it("is a Worker tool: staged by the morning post, offered to no model", () => {
    assert.equal(TOOL_TABLE[PRECEDENCE_INTAKE_TOOL].access, "worker");
  });

  it("the first Approve of the week files it; each later one comments on it, read from the store", async () => {
    const gh = github();
    await addToWeeklyIntake(section("Button"), gh.deps);
    await addToWeeklyIntake(section("TreeSelect"), gh.deps);
    await addToWeeklyIntake(section("Badge"), gh.deps);
    assert.equal(gh.created.length, 1);
    assert.equal(gh.created[0]!.title, "DS precedence, week of Oct 2: code and the library disagree");
    assert.ok(gh.created[0]!.body.startsWith(precedenceMarker("2026-10-02")));
    assert.match(gh.created[0]!.body, /### Button/);
    assert.deepEqual(gh.comments.map((c) => [c.issue_number, c.comment.split("\n")[0]]), [
      [1101, "### TreeSelect"],
      [1101, "### Badge"],
    ]);
    assert.equal(gh.lookups.count, 1, "only the first looks on GitHub");
  });

  it("two Approves back to back make one intake and one comment", async () => {
    const gh = github();
    const results = await Promise.all([addToWeeklyIntake(section("Button"), gh.deps), addToWeeklyIntake(section("TreeSelect"), gh.deps)]);
    for (const r of results) assert.equal(JSON.parse(r).ok, true, r);
    assert.equal(gh.created.length, 1, "one intake");
    assert.equal(gh.comments.length, 1, "the other comments on it");
    assert.equal(gh.comments[0]!.issue_number, 1101);
  });

  it("an intake filed before the store knew of it — closed mid-week, even — is commented on, never filed twice", async () => {
    const closed = { number: 1090, url: `https://github.com/${REPO}/issues/1090`, body: `${precedenceMarker("2026-10-02")}\n\nclosed on Wednesday` };
    const gh = github([closed]);
    await addToWeeklyIntake(section("Button"), gh.deps);
    await addToWeeklyIntake(section("TreeSelect"), gh.deps);
    assert.deepEqual(gh.created, []);
    assert.deepEqual(gh.comments.map((c) => c.issue_number), [1090, 1090]);
    assert.equal(gh.lookups.count, 1, "found once, then read from the store");
  });

  it("a new week files its own intake, whatever last week's left open", async () => {
    const gh = github([{ number: 900, url: "u", body: `${precedenceMarker("2026-09-25")}\n\nlast week` }]);
    await addToWeeklyIntake(section("Button"), gh.deps);
    assert.equal(gh.created.length, 1);
    assert.deepEqual(gh.comments, []);
  });

  it("files nothing when this week's intakes cannot all be read, and the next Approve tries again", async () => {
    const gh = github();
    gh.deps.intakesSince = async () => Promise.reject(new Error("GitHub 502"));
    const result = JSON.parse(await addToWeeklyIntake(section("Button"), gh.deps)) as { ok: boolean; error: string };
    assert.equal(result.ok, false);
    assert.match(result.error, /GitHub 502/);
    gh.deps.intakesSince = async () => ({ intakes: [], complete: false });
    assert.equal(JSON.parse(await addToWeeklyIntake(section("Button"), gh.deps)).ok, false);
    assert.deepEqual(gh.created, []);
    gh.deps.intakesSince = async () => ({ intakes: [], complete: true });
    await addToWeeklyIntake(section("Button"), gh.deps);
    assert.equal(gh.created.length, 1, "the claim was released");
  });
});

// ── Deciding a card ──────────────────────────────────────────────────────────

describe("deciding a weekly card in its Review", () => {
  /** The morning's report posted onto a ThreadState, and a review door whose
   *  Approve runs the card's intake, and whose Needs changes disputes it, on a
   *  fake repo. */
  async function decided() {
    const posted = postDeps(await weekReport());
    await postPrecedenceReport(posted.deps);
    const gh = github([], posted.store);
    const updates: Array<{ ts: string; message: CardMessage }> = [];
    const said: string[] = [];
    const views = recordingViews({ alreadyOpen: ["V1"] });
    const deps: ReviewDoorDeps = {
      threadState: posted.store,
      views: views.client,
      delivery: () => recordingDelivery(),
      applyVerdict: async (v): Promise<OperationOutcome[]> => {
        const outcomes: OperationOutcome[] = [];
        for (const op of v.execute?.operations ?? []) {
          const result = await addToWeeklyIntake(op.input, gh.deps);
          outcomes.push({ toolName: op.toolName, ok: JSON.parse(result).ok !== false, result, message: "Added." });
        }
        return outcomes;
      },
      updateCard: async (_channel, ts, message) => void updates.push({ ts, message }),
      restage: async () => {},
      revise: (request) =>
        disputePrecedenceItem(
          {
            store: posted.store,
            name: async (id) => (id === MEMBERS[0] ? "Maya" : "Bill"),
            write: (input) => addToWeeklyIntake(input, gh.deps),
            edit: async (ts, message) => void updates.push({ ts, message }),
            say: async (text) => void said.push(text),
            now: () => NOW,
          },
          request,
        ),
      now: () => NOW,
    };
    const decide = (id: string, decision: "confirm" | "cancel" | "revise", userId: string, note?: string) =>
      runReviewDecision(
        { viewId: "V1", channel: CHANNEL, messageTs: itemProposal(MSG, id).proposalTs, userId, decision, ...(note ? { note } : {}) },
        deps,
      );
    return { decide, gh, updates, said, views, store: posted.store };
  }

  it("Approve on one card files the week's intake, Approve on the next comments on it, and each card says who decided", async () => {
    const { decide, gh, updates } = await decided();
    await decide("TreeSelect", "confirm", MEMBERS[0]!);
    await decide("Button", "confirm", MEMBERS[1]!);
    assert.equal(gh.created.length, 1, "one intake for the week");
    assert.match(gh.created[0]!.body, /### TreeSelect/);
    assert.equal(gh.comments.length, 1);
    assert.match(gh.comments[0]!.comment, /^### Button/);
    const [button, tree] = cardsIn(updates.at(-1)!.message.blocks);
    assert.match(tree!.subtitle!.text, /^Approved by <@U0MEMBER1> · written /);
    assert.match(button!.subtitle!.text, /^Approved by <@U0MEMBER2> · written /);
    assert.equal(button!.body.text, "Written: added to this week's DS precedence intake.");
    assert.deepEqual(button!.actions.map((a) => a.text.text), ["View", "Code", "Figma"]);
  });

  it("Needs changes disputes the card: its note goes on the week's intake, filing it first, and the card reads Noted by", async () => {
    const { decide, gh, updates, store, views } = await decided();
    await decide("Button", "revise", MEMBERS[0]!, "ghost is library-only on purpose");
    const popUp = JSON.stringify(views.calls.map((c) => c.view));
    assert.match(popUp, /Your note goes on this week's intake\./, "the pop-up says where the note goes");
    assert.doesNotMatch(popUp, /revising the draft/);
    assert.equal(gh.created.length, 1, "no intake yet, so the dispute files it");
    assert.match(gh.created[0]!.body, /\*\*Button\*\*: disputed by Maya — ghost is library-only on purpose/);
    const [button] = cardsIn(updates.at(-1)!.message.blocks);
    assert.equal(button!.subtitle!.text, "Noted by <@U0MEMBER1>");
    assert.equal(button!.body.text, "Note: ghost is library-only on purpose");
    assert.deepEqual(button!.actions.map((a) => a.text.text), ["View", "Code", "Figma"]);
    assert.notEqual((await store.getProposalByTs(itemProposal(MSG, "Button").proposalTs)).state, "found", "nothing else decides it");

    await decide("TreeSelect", "revise", MEMBERS[1]!, "the library is right, code is behind");
    assert.equal(gh.created.length, 1);
    assert.deepEqual(gh.comments.map((c) => c.comment), ["**TreeSelect**: disputed by Bill — the library is right, code is behind"]);
  });

  it("a dispute that does not reach the intake puts the card back to open and says so", async () => {
    const { decide, gh, updates, said, store } = await decided();
    gh.deps.intakesSince = async () => Promise.reject(new Error("GitHub 502"));
    await decide("Button", "revise", MEMBERS[0]!, "deliberate");
    const [button] = cardsIn(updates.at(-1)!.message.blocks);
    assert.equal(button!.subtitle!.text, "Library side");
    assert.deepEqual(button!.actions.map((a) => a.text.text), ["Review", "Code", "Figma"]);
    assert.match(said[0]!, /didn't reach this week's intake/);
    const live = await store.getProposalByTs(itemProposal(MSG, "Button").proposalTs);
    assert.equal(live.state, "found");
    assert.equal(live.state === "found" && live.proposal.revising, undefined, "the lock is lifted");
  });

  it("Reject leaves the difference as deliberate and writes nothing", async () => {
    const { decide, gh, updates } = await decided();
    await decide("Button", "cancel", MEMBERS[0]!, "ghost is library-only on purpose");
    assert.deepEqual(gh.created, []);
    assert.deepEqual(gh.comments, []);
    const [button] = cardsIn(updates.at(-1)!.message.blocks);
    assert.equal(button!.subtitle!.text, "Rejected by <@U0MEMBER1>");
  });

  it("only a #plus-universal member can decide a card", async () => {
    const { decide, gh } = await decided();
    await decide("Button", "confirm", "U0OUTSIDE");
    assert.deepEqual(gh.created, []);
  });
});

describe("the report's thread", () => {
  const env = (reads: string[]) =>
    ({
      PLUS_UNIVERSAL_CHANNEL_ID: CHANNEL,
      HARNESS_KV: {
        get: async (key: string) => {
          reads.push(key);
          return key.endsWith(MSG) ? { channel: CHANNEL, ts: MSG, weekOf: "2026-10-02" } : null;
        },
      },
    }) as unknown as Env;

  it("is known, so its replies are not all turns", async () => {
    assert.equal(await isWeeklyPrecedenceThread(env([]), CHANNEL, MSG), true);
    assert.equal(await isWeeklyPrecedenceThread(env([]), CHANNEL, "1.1"), false);
    const reads: string[] = [];
    assert.equal(await isWeeklyPrecedenceThread(env(reads), "C0OTHER", MSG), false);
    assert.deepEqual(reads, [], "another channel reads nothing");
  });
});
