/**
 * The component tabs' contract — everything the tabs know that does not need a
 * browser to be true (#168).
 *
 * Four tabs over one component page, in Atlassian's order: Examples · Code ·
 * Usage · Changelog. `Examples` is Storybook's own canvas tab, renamed; the
 * other three are registered by `register.jsx` as `types.TAB` addons. Tabs are
 * a HUMAN affordance. The agent-facing file per component stays one flat
 * `index.md` generated by `npm run generate:component-docs`, and nothing here
 * writes to it or splits it.
 *
 * This module is pure on purpose: `design-system/tests/component-tabs-contract.test.js`
 * is the only place the tabs can be checked without a running Storybook.
 */

/** Ids are also URL query values (`?tab=plus-code`), so keep them slug-safe. */
export const TAB_IDS = {
  code: 'plus-code',
  usage: 'plus-usage',
  changelog: 'plus-changelog',
};

/**
 * Titles and order, declared once. Storybook merges this into its tab list via
 * `addons.setConfig({ previewTabs })`, which is also the only supported way to
 * rename the built-in canvas tab — the four-tab shape is one config object
 * rather than four scattered `title` fields.
 */
export const PREVIEW_TABS = {
  canvas: { title: 'Examples', index: 0 },
  [TAB_IDS.code]: { title: 'Code', index: 1 },
  [TAB_IDS.usage]: { title: 'Usage', index: 2 },
  [TAB_IDS.changelog]: { title: 'Changelog', index: 3 },
};

/**
 * The date component changelogs start. Nothing before it is recorded, because
 * nothing produced a component changelog before it — no `CHANGELOG.md`, no
 * changesets, no per-component history convention. An empty changelog is a
 * true statement about this repo; a backfilled one would not be.
 */
export const CHANGELOG_ADOPTED = '2026-08-26';

/** Keep-a-Changelog's categories, minus `security`, which this system has no use for. */
export const CHANGELOG_KINDS = ['added', 'changed', 'deprecated', 'removed', 'fixed'];

const COMPONENTS_ROOT = 'design-system/src/components';

/** Vite reports import paths as `./a/b.jsx`; the repo talks in `a/b.jsx`. */
const repoPath = (p) => String(p).replace(/\\/g, '/').replace(/^\.\//, '');

/** `Button.stories.jsx`, `Button.mdx` and `Button.jsx` all name the component `Button`. */
const componentNameOf = (file) => file.replace(/\.(stories|test)\.[jt]sx?$/, '').replace(/\.(mdx|[jt]sx?)$/, '');

/**
 * Where a Storybook entry sits in the repo, or `null` when it is not a
 * component. Derived from the entry's own `importPath` rather than its sidebar
 * title, because the path is what the generated docs are keyed by — the two
 * agree today, and if they ever stop, the path is the one that can be opened.
 *
 * Both component shapes the doc generator recognises are handled: a nested
 * `<group>/<Name>/<Name>.jsx` documented in `<Name>/index.md`, and a flat
 * `<group>/<Name>.jsx` documented in `<group>/<Name>.md`.
 *
 * @param {{title?: string, importPath?: string}} [entry] A Storybook story or docs entry.
 * @returns {{name: string, group: string, dir: string, source: string,
 *   generatedDoc: string, groupIndex: string, entryFile: string} | null}
 */
export function componentIdentity(entry) {
  if (!entry || typeof entry.importPath !== 'string') return null;

  const entryFile = repoPath(entry.importPath);
  if (!entryFile.startsWith(`${COMPONENTS_ROOT}/`)) return null;

  const segments = entryFile.slice(COMPONENTS_ROOT.length + 1).split('/');
  const group = segments[0];
  const groupIndex = `${COMPONENTS_ROOT}/${group}/index.md`;

  // Nested: <group>/<Name>/<file>. The folder is the component, so a demo file
  // several levels down still resolves to the component that owns it.
  if (segments.length >= 3 && /^[A-Z]/.test(segments[1])) {
    const name = segments[1];
    const dir = `${COMPONENTS_ROOT}/${group}/${name}`;
    return {
      name,
      group,
      dir,
      source: `${dir}/${name}.jsx`,
      generatedDoc: `${dir}/index.md`,
      groupIndex,
      entryFile,
    };
  }

  // Flat: <group>/<Name>.jsx, documented beside itself.
  if (segments.length === 2 && /^[A-Z]/.test(segments[1])) {
    const name = componentNameOf(segments[1]);
    const dir = `${COMPONENTS_ROOT}/${group}`;
    return {
      name,
      group,
      dir,
      source: `${dir}/${name}.jsx`,
      generatedDoc: `${dir}/${name}.md`,
      groupIndex,
      entryFile,
    };
  }

  return null;
}

/**
 * The entries a component declares, newest first. Anything without an ISO date
 * and a summary is dropped rather than rendered half-formed, and an
 * unrecognised `kind` becomes `null` rather than being coerced into one of the
 * five — a changelog that guesses is the failure this mechanism is meant to
 * avoid.
 *
 * @param {unknown} raw The story meta's `parameters.changelog`.
 * @returns {{date: string, kind: string|null, summary: string}[]}
 */
export function normaliseChangelog(raw) {
  if (!Array.isArray(raw)) return [];

  return raw
    .filter(
      (e) =>
        e &&
        typeof e.date === 'string' &&
        /^\d{4}-\d{2}-\d{2}$/.test(e.date) &&
        typeof e.summary === 'string' &&
        e.summary.trim() !== '',
    )
    .map((e) => ({
      date: e.date,
      kind: CHANGELOG_KINDS.includes(e.kind) ? e.kind : null,
      summary: e.summary.trim(),
    }))
    .sort((a, b) => b.date.localeCompare(a.date));
}
