// Build the agent's system prompt as an array of content blocks:
//   - Block 0: the stable skill content (AGENTS.md + SKILL.md files), cached
//     via Anthropic prompt caching. Same content across requests.
//   - Block 1 (optional): per-request pending-proposal context. NOT cached,
//     since it varies per Slack thread + per request.
//
// The harness is baked into the Worker bundle at build time (see
// src/generated/harness.ts, generated by scripts/bundle-harness.mjs) so serving
// it costs ZERO subrequests — it updates on deploy. This replaced the old
// runtime GitHub-Raw fetch (~20 subrequests) that blew the free-tier cap.

import type { Env } from "../types";
import { HARNESS } from "../generated/harness";

export interface PendingContext {
  toolName: string;
  input: Record<string, unknown>;
  requesterUserId: string;
}

export interface SenderContext {
  userId: string;
}

export interface SystemBlock {
  type: "text";
  text: string;
  cache_control?: { type: "ephemeral"; ttl?: "5m" | "1h" };
}

// The harness is baked into the bundle, so serving it is a synchronous constant
// read — zero subrequests, no cache/KV/fetch. It updates on deploy.
// env is unused now but kept for signature stability with existing callers.
function getStableSystem(_env: Env): string {
  return HARNESS;
}

export async function buildSystemBlocks(
  env: Env,
  pending: PendingContext | null,
  sender: SenderContext | null,
  assistantContext?: string | null,
): Promise<SystemBlock[]> {
  const stable = getStableSystem(env);
  // 1h cache TTL on the stable block: design-team traffic gaps blow the 5-min
  // cache TTL; 1h costs 2× on write, pays back on the first reuse within the
  // hour. (ttl is post-SDK-0.32 — SystemBlock carries it; the API accepts it.)
  const blocks: SystemBlock[] = [
    { type: "text", text: stable, cache_control: { type: "ephemeral", ttl: "1h" } },
  ];
  // Per-request, uncached (after the cached stable block so the cache prefix
  // stays stable): who sent the current message. Without this the model knows
  // the whole team roster (harness) but NOT who it's talking to — and a weaker
  // model will guess a roster name for the person speaking ("Hi Meryem!" to
  // Bill, live incident 2026-07-16 on the gemini-2.5-pro fallback lane).
  if (sender && SLACK_USER_ID.test(sender.userId)) {
    blocks.push({ type: "text", text: renderSenderBlock(sender.userId) });
  }
  // Per-request, uncached (varies per thread): what the user has open in the
  // assistant panel. Advisory only — the prompt tells the model not to
  // over-index on it.
  if (assistantContext) {
    blocks.push({ type: "text", text: renderAssistantContextBlock(assistantContext) });
  }
  if (pending) {
    blocks.push({ type: "text", text: renderPendingBlock(pending, sender) });
  }
  return blocks;
}

// Same validation discipline as the panel-context channel id: this string
// lands in a system block, so only a shape-checked Slack user id may pass.
const SLACK_USER_ID = /^[UW][A-Z0-9]{2,20}$/;

function renderSenderBlock(userId: string): string {
  return [
    "<current_sender>",
    `The current message was sent by <@${userId}>.`,
    "Addressing policy (strict, 2026-07-16 after a misaddressed-greeting incident):",
    `- Default: do NOT address the person by any name — "Hey!" beats "Hey <name>!".`,
    `- If addressing them is genuinely needed (e.g. disambiguating between thread participants), use EXACTLY the mention token <@${userId}> and nothing else — Slack renders it as their correct name. Never a plain-text name.`,
    "- You do NOT otherwise know who is speaking. The team-roster names in your instructions are routing candidates (\"who should I ask about X\"), never the identity of the person in this conversation.",
    "</current_sender>",
  ].join("\n");
}

function renderAssistantContextBlock(ctx: string): string {
  return [
    "<assistant_panel_context>",
    `The user is chatting from the assistant panel and currently has this open: ${ctx}.`,
    // Deictic examples must map to real tool lanes: "who's in here" →
    // slack_channel_members, "this channel" → disambiguation only. "What's
    // happening here" was cut — no tool reads a channel's recent history yet.
    'Use this ONLY to disambiguate a vague, deictic ask ("this channel", "who\'s in here") — never assume it is the subject of a specific question. When in doubt, answer the words, not the panel.',
    "</assistant_panel_context>",
  ].join("\n");
}

function renderPendingBlock(p: PendingContext, sender: SenderContext | null): string {
  return [
    "<pending_proposal>",
    "You previously proposed a side-effect action in this Slack thread that is awaiting confirmation:",
    `- tool: ${p.toolName}`,
    `- parameters: ${JSON.stringify(p.input, null, 2)}`,
    `- requester: <@${p.requesterUserId}>`,
    sender ? `- current message sender: <@${sender.userId}>` : "",
    "",
    "If the user's current message clearly confirms or cancels this proposal, invoke the `proposal_resolve` tool. Otherwise reply conversationally and the proposal will sit until ✅, ❌, or 60-minute expiry.",
    "",
    `IMPORTANT: while this proposal is pending, do NOT invoke \`${p.toolName}\` (or any side-effect tool) again for the same action. An approval is handled ONLY by proposal_resolve with decision "confirm" — re-invoking the tool re-stages a duplicate confirmation card instead of executing, which reads as ignoring the user's approval.`,
    "",
    "Authorization: anyone in the thread may confirm or cancel — not just the original requester. A clear go-ahead/cancel from any participant resolves it.",
    "</pending_proposal>",
  ].filter(Boolean).join("\n");
}
