// Build the agent's system prompt as an array of content blocks:
//   - Block 0: the stable skill content (AGENTS.md + SKILL.md files), cached
//     via Anthropic prompt caching. Same content across requests.
//   - Block 1 (optional): per-request pending-proposal context. NOT cached,
//     since it varies per Slack thread + per request.
//
// The harness is baked into the Worker bundle at build time (see
// src/generated/harness.ts, generated by scripts/bundle-harness.mjs) so serving
// it costs ZERO subrequests — it updates on deploy. This replaced the old
// runtime GitHub-Raw fetch (~20 subrequests) that blew the free-tier cap.

import type { Env } from "../types";
import { HARNESS } from "../generated/harness";

export interface PendingContext {
  toolName: string;
  input: Record<string, unknown>;
  requesterUserId: string;
}

export interface SenderContext {
  userId: string;
}

export interface SystemBlock {
  type: "text";
  text: string;
  cache_control?: { type: "ephemeral"; ttl?: "5m" | "1h" };
}

// The harness is baked into the bundle, so serving it is a synchronous constant
// read — zero subrequests, no cache/KV/fetch. It updates on deploy.
// env is unused now but kept for signature stability with existing callers.
function getStableSystem(_env: Env): string {
  return HARNESS;
}

export async function buildSystemBlocks(
  env: Env,
  pending: PendingContext | null,
  sender: SenderContext | null,
): Promise<SystemBlock[]> {
  const stable = getStableSystem(env);
  // 1h cache TTL on the stable block: design-team traffic gaps blow the 5-min
  // cache TTL; 1h costs 2× on write, pays back on the first reuse within the
  // hour. (ttl is post-SDK-0.32 — SystemBlock carries it; the API accepts it.)
  const blocks: SystemBlock[] = [
    { type: "text", text: stable, cache_control: { type: "ephemeral", ttl: "1h" } },
  ];
  if (pending) {
    blocks.push({ type: "text", text: renderPendingBlock(pending, sender) });
  }
  return blocks;
}

function renderPendingBlock(p: PendingContext, sender: SenderContext | null): string {
  return [
    "<pending_proposal>",
    "You previously proposed a side-effect action in this Slack thread that is awaiting confirmation:",
    `- tool: ${p.toolName}`,
    `- parameters: ${JSON.stringify(p.input, null, 2)}`,
    `- requester: <@${p.requesterUserId}>`,
    sender ? `- current message sender: <@${sender.userId}>` : "",
    "",
    "If the user's current message clearly confirms or cancels this proposal, invoke the `proposal_resolve` tool. Otherwise reply conversationally and the proposal will sit until ✅, ❌, or 60-minute expiry.",
    "",
    `IMPORTANT: while this proposal is pending, do NOT invoke \`${p.toolName}\` (or any side-effect tool) again for the same action. An approval is handled ONLY by proposal_resolve with decision "confirm" — re-invoking the tool re-stages a duplicate confirmation card instead of executing, which reads as ignoring the user's approval.`,
    "",
    "Authorization: anyone in the thread may confirm or cancel — not just the original requester. A clear go-ahead/cancel from any participant resolves it.",
    "</pending_proposal>",
  ].filter(Boolean).join("\n");
}
