/**
 * Generate root INDEX.md — the estate's map, derived from frontmatter.
 *
 * Every routable doc declares a `summary:` in its own frontmatter, and this
 * script reads them. Adding a doc changes the index with no second edit; a
 * routable doc with no summary fails the build, because a doc nobody can route
 * to may as well not exist.
 *
 * Usage:
 *   node scripts/generate-index.mjs
 *   node scripts/generate-index.mjs --check   (CI: fail if stale, write nothing)
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const OUT = path.join(REPO_ROOT, 'INDEX.md');
const CHECK = process.argv.includes('--check');

/** Roots whose docs are routable, in the order they appear in the index. */
const SECTIONS = [
  { title: 'Start here', roots: ['README.md', 'SETUP.md', 'AGENTS.md', 'CONTEXT.md', 'loading-order.md'] },
  { title: 'Skills — what humans invoke', roots: ['skills'], depth: 1 },
  { title: 'Agents — what skills summon', roots: ['agents'], depth: 2 },
  { title: 'Connectors — tools an agent can act on', roots: ['docs/connectors'] },
  { title: 'Design system', roots: ['design-system/guidelines'] },
  { title: 'Engineering', roots: ['docs/engineering'] },
  { title: 'Product and service', roots: ['docs/product-and-service'] },
  { title: 'Decisions', roots: ['docs/adr'] },
  { title: 'Conventions', roots: ['docs/conventions'] },
  { title: 'Evals', roots: ['docs/evals/rubrics', 'docs/evals/scenarios'] },
];

/**
 * History and raw material, deliberately unrouted: plans record what was
 * decided, `knowledge/` is being dissolved into rules and ADRs (#172), and eval
 * runs and fixtures are data. Requiring a summary of each would be ceremony.
 */
const NOT_ROUTABLE = [
  'docs/plans', 'docs/knowledge', 'docs/evals/runs', 'docs/evals/fixtures',
  'skills/uno-prototype/examples', 'skills/uno-review/examples',
  'skills/uno-publish/examples', 'skills/uno-maintain/references/skill-quality/examples',
];

/** Reading paths — the one part of this file that is a judgement, not a glob. */
const ROLE_PATHS = [
  ['New here, any role', ['README.md', 'SETUP.md', 'CONTEXT.md']],
  ['Designer building UI', ['design-system/guidelines/overview.md', 'design-system/agent-views/components/index.md', 'design-system/guidelines/composition/layout.md']],
  ['Agent, any task', ['AGENTS.md', 'loading-order.md', 'INDEX.md']],
  ['Working on the harness', ['AGENTS.md', 'docs/adr/overview.md', 'skills/uno-maintain/SKILL.md']],
  ['Working on uno-bot', ['agents/uno-bot/AGENT.md', 'docs/connectors/slack.md', 'docs/engineering/operations.md']],
  ['Writing something long', ['docs/conventions/writing.md', 'docs/connectors/overview.md']],
];

const rel = (p) => path.relative(REPO_ROOT, p).replace(/\\/g, '/');

function frontmatter(abs) {
  const text = fs.readFileSync(abs, 'utf8');
  if (!text.startsWith('---\n')) return {};
  const close = text.indexOf('\n---', 4);
  if (close === -1) return {};
  const meta = {};
  for (const line of text.slice(4, close).split('\n')) {
    const m = line.match(/^([a-zA-Z_-]+):\s*(.*)$/);
    if (m) meta[m[1]] = m[2].trim();
  }
  return meta;
}

function walk(root, depth = Infinity, level = 0) {
  const abs = path.join(REPO_ROOT, root);
  if (!fs.existsSync(abs)) return [];
  if (fs.statSync(abs).isFile()) return root.endsWith('.md') ? [root] : [];
  const out = [];
  for (const entry of fs.readdirSync(abs, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const child = `${root}/${entry.name}`;
    if (NOT_ROUTABLE.some((skip) => child === skip || child.startsWith(`${skip}/`))) continue;
    if (entry.isDirectory()) {
      if (level < depth) out.push(...walk(child, depth, level + 1));
    } else if (entry.name.endsWith('.md')) {
      out.push(child);
    }
  }
  return out;
}

const missing = [];
let doc = `<!-- DO NOT EDIT BY HAND. Generated by npm run generate:index -->\n\n`;
doc += `# plus-uno — index\n\n`;
doc += `Every routable document, with the summary it declares in its own frontmatter.\n`;
doc += `Adding a doc changes this file; editing this file changes nothing.\n\n`;

doc += `## Reading paths\n\n`;
for (const [role, files] of ROLE_PATHS) {
  doc += `**${role}** → ${files.map((f) => `[\`${f}\`](${f})`).join(' → ')}\n\n`;
}

let count = 0;
for (const section of SECTIONS) {
  const files = section.roots.flatMap((r) => walk(r, section.depth ?? Infinity));
  if (!files.length) continue;
  doc += `## ${section.title}\n\n`;
  doc += `| Doc | Summary |\n|-----|---------|\n`;
  for (const f of files) {
    const meta = frontmatter(path.join(REPO_ROOT, f));
    if (!meta.summary) {
      missing.push(f);
      continue;
    }
    doc += `| [\`${f}\`](${f}) | ${meta.summary.replace(/\|/g, '\\|')} |\n`;
    count += 1;
  }
  doc += `\n`;
}

doc += `---\n\n${count} routable documents. History (\`docs/plans/\`, \`docs/knowledge/\`) and\n`;
doc += `raw eval data are deliberately not indexed — they record what happened rather\n`;
doc += `than telling you what to do.\n`;

if (missing.length) {
  console.error(
    `✗ ${missing.length} routable doc(s) declare no \`summary:\` in frontmatter:\n` +
      missing.map((f) => `  ${f}`).join('\n') +
      '\n  -> add `summary: <one line>`, or add the path to NOT_ROUTABLE in this script with the reason.',
  );
  process.exit(1);
}

const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
if (CHECK) {
  if (prev !== doc) {
    console.error('✗ INDEX.md is stale — run `npm run generate:index`.');
    process.exit(1);
  }
  console.log(`✓ INDEX.md up to date (${count} documents)`);
} else {
  if (prev !== doc) fs.writeFileSync(OUT, doc);
  console.log(`✓ INDEX.md (${count} documents)`);
}
