#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the #288 cutover: uno-bot moves to Bill's Cloudflare account.
#
# Cloudflare has no supported transfer of a Worker between accounts, so this is
# a rebuild-and-cut-over. What survives: nothing in the Durable Objects, and
# they mostly do not matter — ThreadState is TTL'd (7d history, 1h proposals,
# 24h dedup) and threaded history is rebuilt from Slack itself; AgentRunner is
# a job queue seconds deep. What must be carried: two KV namespaces, fourteen
# write-only secrets, and the Slack app's registered URLs.
#
# WHAT THIS WIZARD REFUSES TO DO FOR YOU. It never types a secret, never reads
# one back, and never writes one to disk — `npm run secrets:set` takes each on
# your own terminal with echo off and hands it to wrangler on stdin. The only
# values this script persists are four public ids, into an untracked
# .cutover.env, so a re-run resumes and `apply-cutover.mjs` can read them.
#
# RUN IT FROM agents/uno-bot ON THE CUTOVER BRANCH. It stops if you are not.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

BOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$BOT_DIR/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.cutover.env"
# READ, not typed. A second copy of the hostname in a migration script is the
# one place it must not live — this file runs while the host is changing, and
# `check:worker-host` refuses it for exactly that reason. Captured HERE, before
# stage 6 rewrites the files, so stage 11 can still prove the old host is gone.
OLD_HOST="$(node -e "import('$BOT_DIR/scripts/worker-url.mjs').then(m => console.log(new URL(m.DEFAULT_WORKER_ORIGIN).host))" 2>/dev/null)"
OLD_ACCOUNT="$(sed -n 's/^account_id *= *"\(.*\)"/\1/p' "$BOT_DIR/wrangler.toml" | head -n1)"
if [[ -z "$OLD_HOST" || -z "$OLD_ACCOUNT" ]]; then
  printf '  Could not read the current host or account from the repo. Stopping.\n'
  exit 1
fi

cd "$BOT_DIR"

# set_env_secret NAME VALUE — like set_secret, but on the uno-bot-production
# ENVIRONMENT rather than the repo. #310: a repo-level CLOUDFLARE_API_TOKEN is
# readable by any workflow that omits `environment:`, which is the whole reason
# the environment exists.
set_env_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env uno-bot-production >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name (uno-bot-production)")
      printf '  %s✓ set%s %s on the uno-bot-production environment\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("$name on uno-bot-production (gh secret set $name --env uno-bot-production)")
  warn "skipped $name: gh not ready. Set it by hand before merging."
}

# ask_required KEY "Prompt" — `ask`, but an empty answer is not an answer.
#
# WHY. The library's `ask` accepts "" and hands it straight to `write_env`, so a
# run with no one at the keyboard (a pipe, a closed stdin, an impatient Enter)
# walks the whole eleven stages writing blanks and only fails at the end, in
# apply-cutover, having already opened six browser tabs. Three tries, then stop:
# a bounded loop, so a non-interactive run terminates instead of spinning.
ask_required() {
  local key="$1" prompt="$2" attempt
  for attempt in 1 2 3; do
    ask "$key" "$prompt"
    [[ -n "${!key}" ]] && return 0
    warn "That is empty, and an empty value would be written to the repo."
  done
  warn "No value after three tries. Stopping rather than recording a blank."
  exit 1
}

banner "uno-bot → your Cloudflare account (#288)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this needs, and where you are standing."
for tool in node wrangler gh git; do
  if command -v "$tool" >/dev/null 2>&1 || [[ "$tool" == wrangler && -x "$BOT_DIR/node_modules/.bin/wrangler" ]]; then
    note "✓ $tool"
  else
    warn "$tool is missing. Install it and re-run."
    exit 1
  fi
done
WRANGLER="$BOT_DIR/node_modules/.bin/wrangler"
[[ -x "$WRANGLER" ]] || WRANGLER="wrangler"

# `command -v node` proves nothing: wrangler declares a Node floor and refuses
# to run below it, with an error that reads like advice rather than a stop.
# The floor is READ from the installed wrangler's engines field, so this cannot
# drift from the wrangler this repo actually pins.
NODE_FLOOR="$(node -e "
  try {
    const e = require('$BOT_DIR/node_modules/wrangler/package.json').engines || {};
    const m = /(\\d+)/.exec(e.node || '');
    if (m) console.log(m[1]);
  } catch {}
" 2>/dev/null)"
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null)"
if [[ -n "$NODE_FLOOR" && -n "$NODE_MAJOR" && "$NODE_MAJOR" -lt "$NODE_FLOOR" ]]; then
  warn "node $(node -v) is below wrangler's floor of v${NODE_FLOOR}."
  note "  Every wrangler call in this wizard would fail, several of them quietly."
  # Naming the version that is already installed beats naming a manager: it is
  # one line to paste rather than a search.
  READY=""
  for candidate in "$HOME"/.nvm/versions/node/v*/bin/node; do
    [[ -x "$candidate" ]] || continue
    major="$("$candidate" -p 'process.versions.node.split(".")[0]' 2>/dev/null)"
    # The LOWEST satisfying version, not the newest: the smallest step away
    # from the Node this repo is otherwise run on.
    [[ -n "$major" && "$major" -ge "$NODE_FLOOR" && -z "$READY" ]] && READY="$("$candidate" -v)"
  done
  if [[ -n "$READY" ]]; then
    note "  You already have $READY installed. In this shell:"
    note "    nvm use ${READY#v}"
  else
    note "  Install one: nvm install $NODE_FLOOR   (or volta install node@$NODE_FLOOR)"
  fi
  note "  Then re-run this wizard. It resumes from what is already in .cutover.env."
  exit 1
fi
note "✓ node $(node -v) (wrangler needs v${NODE_FLOOR:-?}+)"

BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)"
note "branch: $BRANCH"
if [[ "$BRANCH" == "main" ]]; then
  warn "You are on main. Merging main DEPLOYS — make a cutover branch first:"
  note "  git checkout -b chore/288-cutover"
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Log in as yourself, and read the account id"
say "wrangler needs to be authenticated as the account the Worker is moving TO."
note "This opens a browser. Pick YOUR account, not the current one."
confirm "Run 'wrangler login' now? (skip if already logged in as yourself)" && "$WRANGLER" login || true
say ""
say "Reading the accounts this login can see:"
if ! "$WRANGLER" whoami; then
  warn "wrangler whoami failed, so the account list above is not there."
  note "  The next question asks you to copy an Account ID out of that list."
  note "  Answering it from memory is how the wrong id gets written into seven"
  note "  files, so this stops here instead. Fix the login and re-run."
  exit 1
fi
say ""
step "Copy the Account ID of the account you are moving INTO."
warn "It must NOT be $OLD_ACCOUNT — that is the account you are leaving."
ask_required NEW_ACCOUNT_ID "Paste the new Account ID:"
if [[ "$NEW_ACCOUNT_ID" == "$OLD_ACCOUNT" ]]; then
  warn "That is the old account. Nothing to move. Stopping."
  exit 1
fi
write_env NEW_ACCOUNT_ID "$NEW_ACCOUNT_ID"
export CLOUDFLARE_ACCOUNT_ID="$NEW_ACCOUNT_ID"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enumerate the secrets that are actually set"
say "Cloudflare secrets cannot be read back — no export exists, for anyone."
say "So the LIST matters: wrangler.toml's expected-secrets comment is already"
say "incomplete (the live Worker carries an ANTHROPIC_API_KEY it does not name)."
say ""
if confirm "Do you have access to the OLD account (to list its secret NAMES)?"; then
  step "Listing names only — values are never shown, by anyone, ever."
  CLOUDFLARE_ACCOUNT_ID="$OLD_ACCOUNT" "$WRANGLER" secret list --name uno-bot 2>/dev/null \
    || warn "Could not list. Use the dashboard: Workers → uno-bot → Settings → Variables."
else
  note "Then work from scripts/secrets.mjs (14 declared) and check the old"
  note "dashboard's Variables tab for anything it does not name."
fi
say ""
warn "GEMINI_API_KEY must stay UNSET. The Vertex SA is canonical (ADR-018); the"
warn "AI Studio key cannot reach Claude and its presence silently changes the lane."
pause "Noted the list? Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the two KV namespaces"
say "SLACK_OAUTH_KV holds the issued Slack user token and the PKCE verifiers."
say "HARNESS_KV holds the figma-poll snapshot, the delivery-alert throttle and"
say "the Gemini cache memo. Both are small."
say ""
# WRANGLER.TOML'S account_id BEATS $CLOUDFLARE_ACCOUNT_ID, and stage 2 only
# exported the variable. So every wrangler call made from this directory was
# still talking to the account we are LEAVING — its account_id line is not
# rewritten until stage 6, which needs these ids and therefore runs after.
#
# Proven, read-only, both ways:
#   wrangler kv namespace list                    -> the old account's namespaces
#   wrangler kv namespace list -c <no account_id> -> []
#
# The fix is a throwaway config carrying no account_id, so the env var is the
# only thing left to answer the question. The real wrangler.toml is not touched
# here: rewriting it early would make apply-cutover read the NEW account as its
# OLD one and refuse the whole pass.
# `mktemp` creates its own extensionless file and wrangler needs the .toml
# suffix to parse it, so both names exist and both have to go.
# `mktemp` creates its own extensionless file and wrangler needs the .toml
# suffix to parse it, so both names exist and both have to go. Two variables,
# because the trap body expands at EXIT: one that also held the base name would
# by then have been reassigned, and the base would survive.
MINI_BASE="$(mktemp -t cutover-wrangler)"
MINI_TOML="$MINI_BASE.toml"
trap 'rm -f "$MINI_BASE" "$MINI_TOML"' EXIT
{
  printf 'name = "uno-bot"\n'
  # Carried across rather than pinned, so this cannot drift from the real config.
  sed -n 's/^compatibility_date *= *\(".*"\)/compatibility_date = \1/p' "$BOT_DIR/wrangler.toml" | head -n1
} > "$MINI_TOML"

# kv_namespace_id TITLE — create it in the new account and return its id, or
# find the id if it is already there from an earlier run. Never asks a human to
# read an id out of scrollback: that is how an id from the wrong account gets
# typed in, which is the exact failure this whole cutover exists to undo.
kv_namespace_id() {
  local title="$1" out id
  out="$(CLOUDFLARE_ACCOUNT_ID="$NEW_ACCOUNT_ID" "$WRANGLER" kv namespace create "$title" -c "$MINI_TOML" 2>&1)" || true
  id="$(printf '%s' "$out" | sed -n 's/.*id *= *"\([0-9a-f]\{32\}\)".*/\1/p' | head -n1)"
  if [[ -z "$id" ]]; then
    # Already exists is the normal case on a re-run, not an error.
    id="$(CLOUDFLARE_ACCOUNT_ID="$NEW_ACCOUNT_ID" "$WRANGLER" kv namespace list -c "$MINI_TOML" 2>/dev/null \
      | node -e "
        let s = ''; process.stdin.on('data', c => s += c).on('end', () => {
          try {
            const hit = JSON.parse(s.slice(s.indexOf('['))).find(n => n.title === '$title');
            if (hit) console.log(hit.id);
          } catch {}
        });
      " 2>/dev/null)"
  fi
  printf '%s' "$id"
}

step "Creating them in $NEW_ACCOUNT_ID:"
NEW_SLACK_OAUTH_KV_ID="$(kv_namespace_id SLACK_OAUTH_KV)"
NEW_HARNESS_KV_ID="$(kv_namespace_id HARNESS_KV)"

# The old ids come from apply-cutover, which already parses them BY BINDING —
# one parser, so the two cannot disagree about which namespace is which.
OLD_SLACK_KV="$(node -e "import('$BOT_DIR/scripts/apply-cutover.mjs').then(m => console.log(m.OLD.slackKv))" 2>/dev/null)"
OLD_HARNESS_KV="$(node -e "import('$BOT_DIR/scripts/apply-cutover.mjs').then(m => console.log(m.OLD.harnessKv))" 2>/dev/null)"

for pair in "SLACK_OAUTH_KV:$NEW_SLACK_OAUTH_KV_ID:$OLD_SLACK_KV" "HARNESS_KV:$NEW_HARNESS_KV_ID:$OLD_HARNESS_KV"; do
  kv_title="${pair%%:*}"; kv_rest="${pair#*:}"; kv_new="${kv_rest%%:*}"; kv_old="${kv_rest#*:}"
  if [[ -z "$kv_new" ]]; then
    warn "Could not create or find $kv_title in $NEW_ACCOUNT_ID."
    note "  Make it in the dashboard (Storage & Databases -> KV) and re-run;"
    note "  this stage will then find it instead of creating it."
    exit 1
  fi
  if [[ "$kv_new" == "$kv_old" ]]; then
    warn "$kv_title came back as $kv_new — the id already in wrangler.toml."
    note "  That means wrangler answered from the OLD account. Stopping: writing"
    note "  this id would leave the Worker reading the account you are leaving."
    exit 1
  fi
  note "✓ $kv_title = $kv_new"
done

write_env NEW_SLACK_OAUTH_KV_ID "$NEW_SLACK_OAUTH_KV_ID"
write_env NEW_HARNESS_KV_ID "$NEW_HARNESS_KV_ID"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Carry the KV contents, or decide not to"
say "Losing them costs: one re-run of /oauth/slack/start for the Slack token,"
say "and one spurious 'everything changed' figma-poll card the next time the"
say "cron fires against an empty snapshot."
say ""
if confirm "Copy the contents across? (needs access to the old account)"; then
  step "For each namespace: wrangler kv key list, then get/put each key."
  note "  CLOUDFLARE_ACCOUNT_ID=$OLD_ACCOUNT $WRANGLER kv key list --namespace-id=18b58372d9bc430489d634c2c9a0b0c4"
  note "  CLOUDFLARE_ACCOUNT_ID=$NEW_ACCOUNT_ID $WRANGLER kv key put --namespace-id=$NEW_SLACK_OAUTH_KV_ID <key> <value>"
  warn "Not scripted here on purpose: it reads a live OAuth token, and a loop"
  warn "that pipes secrets through your shell history is not worth the minute."
  pause "Copy what you want, then Enter"
else
  note "Skipped. Re-consent after cutover: hit /oauth/slack/start once."
  SKIPPED+=("KV contents not copied — re-run /oauth/slack/start after cutover")
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Rewrite the repo to point at the new account"
say "Seven files name the old account, the old KV ids or the old hostname."
say "The hostname is not known until the first deploy, so this asks for it now"
say "in the form Cloudflare will give you: uno-bot.<your-subdomain>.workers.dev"
say ""
open_url "https://dash.cloudflare.com/$NEW_ACCOUNT_ID/workers/subdomain"
step "That page shows your workers.dev subdomain. The Worker will be at"
step "  uno-bot.<subdomain>.workers.dev"
ask_required NEW_WORKER_HOST "New hostname (no https://):"
say ""
# CHECKED BEFORE IT IS WRITTEN. Persisting first means a rejected value comes
# back as the "[Enter keeps current]" default on the next run, so one typo
# becomes the answer for every re-run after it.
NEW_WORKER_HOST="${NEW_WORKER_HOST#http://}"
NEW_WORKER_HOST="${NEW_WORKER_HOST#https://}"
NEW_WORKER_HOST="${NEW_WORKER_HOST%/}"
node "$BOT_DIR/scripts/apply-cutover.mjs" --check --host="$NEW_WORKER_HOST" \
  || { warn "apply-cutover refused. Read it above; nothing was written, and the"; \
       note "  hostname was NOT saved, so re-running asks again."; exit 1; }
write_env NEW_WORKER_HOST "$NEW_WORKER_HOST"
say ""
if confirm "Apply those rewrites now?"; then
  node "$BOT_DIR/scripts/apply-cutover.mjs"
  note "Read 'git diff' before you commit. Do NOT merge yet — merging deploys."
else
  SKIPPED+=("repo rewrite (node agents/uno-bot/scripts/apply-cutover.mjs)")
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "First deploy — this is what creates the Worker"
say "The Worker, its Durable Objects and its cron do not exist in the new"
say "account until something deploys. Secrets cannot be set before it does."
say ""
warn "npm run deploy runs the gates first: typecheck, fetch, contract, secrets,"
warn "bundle. If the blueprint sibling checkout is missing, the contract gate"
warn "fails — BLUEPRINT_CONTRACT_OPTIONAL=1 is the documented escape hatch."
say ""
if confirm "Run the deploy now?"; then
  ( cd "$BOT_DIR" && npm run deploy ) || {
    warn "Deploy failed. If it was the contract gate, retry with:"
    note "  BLUEPRINT_CONTRACT_OPTIONAL=1 npm run deploy"
    pause "Enter when it has succeeded"
  }
else
  SKIPPED+=("first deploy (npm run deploy from agents/uno-bot)")
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Set every secret, on your own terminal"
say "This is the bulk of the work and the least risky part. Each value is typed"
say "with echo off and handed to wrangler on stdin — never argv (visible to ps),"
say "never a file, never this script's memory."
say ""
step "npm run secrets:set -- --all   prompts for every declared secret"
note "The Vertex PEM is multi-line: it prints the pipe-from-file command instead."
say ""
if confirm "Run it now?"; then
  ( cd "$BOT_DIR" && npm run secrets:set -- --all ) || warn "Some secrets did not land. Re-run 'npm run secrets:set' — it only asks for what is missing."
else
  SKIPPED+=("secrets (npm run secrets:set -- --all)")
fi
say ""
step "Redeploy so the Worker picks them up:"
confirm "Redeploy now?" && ( cd "$BOT_DIR" && npm run deploy ) || true
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Repoint the Slack app — the slowest step"
say "pkce_enabled permanently disabled apps.manifest.update for this app"
say "(ADR-024), so no script can push this. The manifests in the repo are now"
say "rewritten to the new host and are the thing you paste."
say ""
open_url "https://api.slack.com/apps/A0APS0L8HJR/app-manifest"
step "That is the uno-bot app's manifest editor (team T0C5GFUPJ)."
step "Paste agents/uno-bot/slack-app-manifest.yaml, save."
step "Then the command half: agents/uno-bot/slack-app-manifest-commands.yaml."
step "Check Event Subscriptions and Interactivity both show the new host."
step "Check OAuth & Permissions → Redirect URLs matches EXACTLY:"
note "  https://$NEW_WORKER_HOST/oauth/slack/callback"
say ""
pause "Pasted and saved? Enter to verify"
if confirm "Run 'npm run slack:diff' to compare the live app against the repo?"; then
  ( cd "$BOT_DIR" && npm run slack:diff ) || warn "Differences above. The live app is what matters — fix it there."
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "GitHub: the deploy token, on the environment"
say "CI deploys with an API token scoped to the new account. It goes on the"
say "uno-bot-production ENVIRONMENT, not the repo — #310: a repo-level token is"
say "readable by any workflow that omits 'environment:'."
say ""
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → 'Edit Cloudflare Workers' template."
step "Account Resources: the NEW account only. Zone Resources: none needed."
step "Create, then copy it — Cloudflare shows it once."
ask_secret NEW_CLOUDFLARE_API_TOKEN "Paste the new API token (hidden):"
if [[ -n "$NEW_CLOUDFLARE_API_TOKEN" ]]; then
  set_env_secret CLOUDFLARE_API_TOKEN "$NEW_CLOUDFLARE_API_TOKEN"
  NEW_CLOUDFLARE_API_TOKEN=""
else
  SKIPPED+=("CLOUDFLARE_API_TOKEN on uno-bot-production")
fi
say ""
step "Point CI's health checks at the new host — a variable, not a commit:"
set_var UNO_BOT_WORKER_URL "https://$NEW_WORKER_HOST"
say ""
warn "#310: delete the REPO-level CLOUDFLARE_API_TOKEN once the environment one works."
note "  gh secret delete CLOUDFLARE_API_TOKEN"
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Verify — and only then merge"
say "Five checks. Each one has been a real failure at least once."
say ""
step "1. Build stamp — 'unstamped' means the gates did not run (#278):"
note "   curl -s https://$NEW_WORKER_HOST/health"
curl -fsS --max-time 15 "https://$NEW_WORKER_HOST/health" 2>/dev/null | sed 's/^/     /' || warn "     no answer yet"
say ""
step "2. Supabase reachable:"
note "   curl -s https://$NEW_WORKER_HOST/health/blueprint   (all probes true)"
say ""
step "3. The old host appears nowhere it should not:"
( cd "$BOT_DIR" && node scripts/check-worker-host.mjs --host="$OLD_HOST" ) || warn "     still referenced above — fix before merging"
say ""
step "4. A real Slack thread: ask something, expect a grounded answer with links."
step "5. GET /$NEW_WORKER_HOST/debug/figma-poll fires without a spurious card,"
step "   and the Cloudflare dashboard shows a Next run for the cron."
say ""
warn "Only now merge the branch. The deploy's 150s hold (#285) confirms the new"
warn "Worker is serving and STAYS serving before the run goes green."
say ""
note "Rollback: the old Worker is still deployed. Revert the branch and redeploy."
note "Decommission after a week: delete it, then revoke the old API token."
pause

finish
