#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — everything the #288 cutover still needs, in one pass.
#
# The Worker is already deployed under the new account and eight of the ten
# secrets are on it. What is left is the tail nobody can script away: two
# secrets, a Slack manifest that must be pasted by hand (ADR-024), a deploy
# token, and the checks that prove the move actually worked.
#
# EVERY STAGE SKIPS ITSELF WHEN IT IS ALREADY DONE. State is read from the
# Worker and the repo, never from a file this script keeps, so it is safe to
# Ctrl-C at any point and safe to run twice.
#
# NOTHING HERE IS HARDCODED. The account comes from wrangler.toml, the host
# from scripts/worker-url.mjs — a second copy of the hostname is what
# check:worker-host exists to prevent, and a cutover script is the worst place
# to keep one.
#
# RUN IT FROM agents/uno-bot ON THE CUTOVER BRANCH: wrangler.toml is what names
# the account, so the branch decides which Worker everything lands on.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

BOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$BOT_DIR/../.." && pwd)"
cd "$BOT_DIR"

WRANGLER="$BOT_DIR/node_modules/.bin/wrangler"
[[ -x "$WRANGLER" ]] || WRANGLER="wrangler"

ACCOUNT="$(sed -n 's/^account_id *= *"\(.*\)"/\1/p' "$BOT_DIR/wrangler.toml" | head -n1)"
ORIGIN="$(node -e "import('$BOT_DIR/scripts/worker-url.mjs').then(m => console.log(m.DEFAULT_WORKER_ORIGIN))" 2>/dev/null)"
BRANCH="$(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)"

# The team and app ids are already written down once, in the slack:diff script.
# Parsed from there rather than repeated here, for the same reason the hostname
# is read from worker-url.mjs.
SLACK_TEAM="$(node -p "(/--team (\S+)/.exec(require('$BOT_DIR/package.json').scripts['slack:diff'])||[])[1]||''" 2>/dev/null)"
SLACK_APP="$(node -p "(/--app (\S+)/.exec(require('$BOT_DIR/package.json').scripts['slack:diff'])||[])[1]||''" 2>/dev/null)"

# put_secret NAME — reads the value on stdin, hands it to wrangler there.
# Never an argv entry: argv is readable by `ps` for every user on the machine.
# It only REPORTS; the caller records, because the right-hand side of a
# pipeline runs in a subshell and an array grown there is discarded on exit.
put_secret() {
  local name="$1"
  if "$WRANGLER" secret put "$name" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  warn "wrangler refused $name. Nothing was written."
  return 1
}

already_set() { "$WRANGLER" secret list 2>/dev/null | grep -q "\"$1\""; }

# find_blueprint — `npm run deploy` runs check:contract, which compares the
# vendored blueprint contract against the CANONICAL copy in the uno-blueprint
# app repo. Its default path is relative to the script, which does not resolve
# from a git worktree, so the deploy dies at the third gate with
# "blueprint contract not found ... (set BLUEPRINT_REPO)" AFTER the secrets are
# already in — a stop with nothing wrong and no obvious next move.
#
# So: honour an existing BLUEPRINT_REPO, else look where the checkout actually
# tends to live, else ask. A checkout is identified by the contract file itself
# rather than by its directory name, because the name has been both
# uno-blueprint and plus-uno-blueprint.
find_blueprint() {
  local candidate
  for candidate in \
    "${BLUEPRINT_REPO:-}" \
    "$REPO_ROOT/../plus-uno-blueprint" \
    "$REPO_ROOT/../uno-blueprint" \
    "$REPO_ROOT/uno-blueprint" \
    "$HOME/Desktop/PLUS/plus-uno-blueprint"
  do
    [[ -n "$candidate" && -f "$candidate/src/lib/blueprintContract.ts" ]] || continue
    printf '%s' "$(cd "$candidate" && pwd)"
    return 0
  done
  return 1
}

# deploy_bot — one place that knows how to run the deploy, so every stage that
# offers it offers the same one.
deploy_bot() {
  local found
  if found="$(find_blueprint)"; then
    export BLUEPRINT_REPO="$found"
    note "blueprint contract: $BLUEPRINT_REPO"
  else
    warn "No uno-blueprint checkout found, so check:contract cannot compare."
    note "  The contract gate is what stops the Worker shipping against a"
    note "  blueprint schema it no longer matches (#258)."
    ask BLUEPRINT_REPO_INPUT "Path to a uno-blueprint checkout (blank to skip the gate):"
    if [[ -n "$BLUEPRINT_REPO_INPUT" && -f "$BLUEPRINT_REPO_INPUT/src/lib/blueprintContract.ts" ]]; then
      export BLUEPRINT_REPO="$BLUEPRINT_REPO_INPUT"
    else
      [[ -n "$BLUEPRINT_REPO_INPUT" ]] && warn "No blueprintContract.ts under that path."
      warn "Deploying with the contract gate DISARMED."
      SKIPPED+=("check:contract ran disarmed — no blueprint checkout to compare against")
      export BLUEPRINT_CONTRACT_OPTIONAL=1
    fi
  fi
  ( cd "$BOT_DIR" && npm run deploy )
}

# ask_multiline NAME — for a secret that spans lines and is NOT in a file:
# a PEM copied out of a Notion page, say. A no-echo prompt cannot take a paste
# with newlines in it, so this opens an editor on a 0600 temp file instead,
# pipes the saved contents to wrangler, and overwrites the file before removing
# it. The value never reaches the terminal, argv, or shell history.
ask_multiline() {
  local name="$1" tmp status
  umask 077
  tmp="$(mktemp -t cutover-secret)"
  printf '\n' > "$tmp"
  note "Opening ${EDITOR:-nano}. Paste the value, save, and close."
  note "  The file is mode 600 and is shredded the moment this is done."
  pause "Enter to open the editor"
  "${EDITOR:-nano}" "$tmp" || true
  # A trailing newline the editor added is fine for a PEM and wrong for a
  # token, so it is stripped and the PEM's own final newline restored below.
  if [[ ! -s "$tmp" ]]; then
    warn "Nothing was saved. $name not set."
    rm -f "$tmp"
    return 1
  fi
  if grep -q "BEGIN" "$tmp"; then
    note "Looks like a PEM ($(grep -c '' "$tmp") lines)."
  else
    printf '%s' "$(cat "$tmp")" > "$tmp.trimmed" && mv "$tmp.trimmed" "$tmp"
  fi
  put_secret "$name" < "$tmp"
  status=$?
  # Overwrite before unlinking: rm alone leaves the bytes on disk.
  dd if=/dev/urandom of="$tmp" bs=1k count=8 conv=notrunc 2>/dev/null || true
  rm -f "$tmp" "$tmp.trimmed"
  return $status
}

banner "uno-bot: finish the #288 cutover"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Where this actually is"
note "account: $ACCOUNT"
note "branch:  $BRANCH"
note "host:    $ORIGIN"
if [[ "$BRANCH" == "main" ]]; then
  warn "You are on main. Merging main DEPLOYS. Switch to the cutover branch."
  exit 1
fi
say ""
say "Worker:"
if curl -sf --max-time 15 "$ORIGIN/health" >/dev/null 2>&1; then
  note "  ✓ $ORIGIN/health -> $(curl -s --max-time 15 "$ORIGIN/health")"
else
  warn "  $ORIGIN/health is not answering."
  note "  If the subdomain changed in the last few minutes this is DNS caching"
  note "  on THIS machine — check the URL in a browser before believing it."
fi
say ""
say "Secrets:"
( cd "$BOT_DIR" && npm run --silent secrets:audit ) || true
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "The two secrets that were passed over"
say "set-secrets calls these optional, so it never asked. They are set on the"
say "account being left, so skipping them is a downgrade rather than a move."
say ""
if already_set SUPABASE_ANON_KEY; then
  note "✓ SUPABASE_ANON_KEY already set."
else
  SUPA="$(sed -n 's|^SUPABASE_URL *= *"https://\([^.]*\)\..*|\1|p' "$BOT_DIR/wrangler.toml" | head -n1)"
  say "SEMANTIC_SEARCH and BLUEPRINT_HYBRID are both \"on\" against $SUPA."
  say "Without this key both go dark while the Worker still boots."
  open_url "https://supabase.com/dashboard/project/$SUPA/settings/api"
  step "Copy the anon / public key."
  warn "NOT service_role — that one bypasses row-level security."
  ask_secret SUPA_VALUE "Paste the anon key (hidden):"
  if [[ -n "$SUPA_VALUE" ]]; then
    if printf '%s' "$SUPA_VALUE" | put_secret SUPABASE_ANON_KEY; then
      WRITTEN_SECRET+=("SUPABASE_ANON_KEY"); else SKIPPED+=("SUPABASE_ANON_KEY"); fi
  else
    SKIPPED+=("SUPABASE_ANON_KEY")
  fi
  unset SUPA_VALUE
fi
say ""
if already_set SLACK_MCP_CLIENT_SECRET; then
  note "✓ SLACK_MCP_CLIENT_SECRET already set."
else
  say "The client half of the Slack MCP OAuth flow — workspace search."
  open_url "https://app.slack.com/app-settings/$SLACK_TEAM/$SLACK_APP/general"
  step "Basic Information -> App Credentials -> Client Secret -> Show."
  warn "Show, not Regenerate: the old Worker is still the live bot on this app."
  ask_secret MCP_VALUE "Paste the client secret (hidden):"
  if [[ -n "$MCP_VALUE" ]]; then
    if printf '%s' "$MCP_VALUE" | put_secret SLACK_MCP_CLIENT_SECRET; then
      WRITTEN_SECRET+=("SLACK_MCP_CLIENT_SECRET"); else SKIPPED+=("SLACK_MCP_CLIENT_SECRET"); fi
  else
    SKIPPED+=("SLACK_MCP_CLIENT_SECRET")
  fi
  unset MCP_VALUE
fi
say ""
note "Any multi-line secret that needs redoing (the Vertex PEM, say) can go in"
note "through an editor instead of a prompt: re-run with --fix-pem."
if [[ "${1:-}" == "--fix-pem" ]]; then
  say ""
  say "Redoing GEMINI_SA_PRIVATE_KEY. Two routes:"
  step "a downloaded service-account JSON — give the path, and .private_key is"
  step "  extracted with its \\n escapes turned into real newlines"
  step "or blank, and an editor opens for you to paste the key block"
  ask SA_JSON_PATH "Path to the service-account JSON (blank for the editor):"
  # Drag-and-drop leaves a trailing space and escapes; a quoted paste leaves
  # the quotes. Both are how this actually gets typed.
  SA_JSON_PATH="${SA_JSON_PATH%\"}"; SA_JSON_PATH="${SA_JSON_PATH#\"}"
  SA_JSON_PATH="${SA_JSON_PATH%\'}"; SA_JSON_PATH="${SA_JSON_PATH#\'}"
  SA_JSON_PATH="$(printf '%s' "$SA_JSON_PATH" | sed 's/[[:space:]]*$//; s/\\ / /g')"
  SA_JSON_PATH="${SA_JSON_PATH/#\~/$HOME}"

  if [[ -z "$SA_JSON_PATH" ]]; then
    ask_multiline GEMINI_SA_PRIVATE_KEY && WRITTEN_SECRET+=("GEMINI_SA_PRIVATE_KEY")
  elif [[ ! -f "$SA_JSON_PATH" ]]; then
    warn "No file at: $SA_JSON_PATH. Nothing sent."
  else
    # Read once, and report only what is safe to show: never the key.
    SA_SUMMARY="$(node -e "
      const fs = require('fs');
      let d;
      try { d = JSON.parse(fs.readFileSync(process.argv[1], 'utf8')); }
      catch { console.log('BAD_JSON'); process.exit(0); }
      if (d.type !== 'service_account') { console.log('NOT_SA:' + (d.type || 'no type field')); process.exit(0); }
      if (!d.private_key || !d.private_key.includes('BEGIN')) { console.log('NO_KEY'); process.exit(0); }
      console.log(['OK', d.client_email || '?', d.project_id || '?', d.private_key_id || '?'].join('|'));
    " "$SA_JSON_PATH")"
    case "$SA_SUMMARY" in
      BAD_JSON) warn "Not valid JSON. Nothing sent." ;;
      NOT_SA:*) warn "Not a service account (type: ${SA_SUMMARY#NOT_SA:}). Nothing sent."
                note "  You want the key file from IAM & Admin -> Service Accounts -> Keys." ;;
      NO_KEY)   warn "No private_key in that JSON. Nothing sent." ;;
      *)
        note "  service account: $(printf '%s' "$SA_SUMMARY" | cut -d'|' -f2)"
        note "  project:         $(printf '%s' "$SA_SUMMARY" | cut -d'|' -f3)"
        note "  key id:          $(printf '%s' "$SA_SUMMARY" | cut -d'|' -f4)"
        warn "If that key id is one that has ever been pasted into a chat, an"
        warn "issue, or a document, delete it in Google Cloud and use a new one."
        if confirm "Set GEMINI_SA_PRIVATE_KEY from this file?"; then
          if node -e "
            const fs = require('fs');
            process.stdout.write(JSON.parse(fs.readFileSync(process.argv[1], 'utf8')).private_key);
          " "$SA_JSON_PATH" | put_secret GEMINI_SA_PRIVATE_KEY; then
            WRITTEN_SECRET+=("GEMINI_SA_PRIVATE_KEY")
          else
            SKIPPED+=("GEMINI_SA_PRIVATE_KEY")
          fi
        fi ;;
    esac
  fi
fi
say ""
say "Secrets only take effect on the next deploy."
confirm "Deploy now?" && { deploy_bot || warn "Deploy failed. Read it above; the secrets are still set — re-run this wizard and it will skip straight past them."; }
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Prove the model lane actually works"
say "GEMINI_SA_PRIVATE_KEY is the one secret that can be SET and still wrong:"
say "a PEM pasted with its \\n escapes intact stores fine and fails at runtime"
say "with a signing error. /debug/gemini is what tells the difference."
say ""
say ""
say "First, the probe that needs no token — table reachability only, no rows:"
BP_CODE="$(curl -s --max-time 30 -o /tmp/uno-bp.$$ -w '%{http_code}' "$ORIGIN/health/blueprint" || echo 000)"
note "  /health/blueprint -> $BP_CODE"
head -c 400 "/tmp/uno-bp.$$" 2>/dev/null | sed 's/^/      /'; printf '\n'
rm -f "/tmp/uno-bp.$$"
if [[ "$BP_CODE" == "503" ]]; then
  note "  503 means SUPABASE_ANON_KEY is not set, or the deploy that would have"
  note "  picked it up has not run yet."
fi
say ""
say "DEBUG_TOKEN is the value you chose. It is used here and not stored."
ask_secret DEBUG_VALUE "DEBUG_TOKEN (hidden):"
if [[ -n "$DEBUG_VALUE" ]]; then
  for route in gemini vertex-claude blueprint; do
    # x-debug-token, NOT Authorization: Bearer. debugAuthorized() reads that
    # header and nothing else, and a failed compare returns 404 rather than 401
    # by design — an unauthenticated caller must not be able to confirm the
    # route exists. So a 404 here means the TOKEN is wrong far more often than
    # the route is missing, and the first draft of this stage sent the wrong
    # header and read its own three 404s as a broken deploy.
    code="$(curl -s --max-time 45 -o /tmp/uno-debug.$$ -w '%{http_code}' \
      -H "x-debug-token: $DEBUG_VALUE" "$ORIGIN/debug/$route" || echo 000)"
    if [[ "$code" == "200" ]]; then
      note "  ✓ /debug/$route -> 200"
    elif [[ "$code" == "404" ]]; then
      warn "  /debug/$route -> 404"
      note "      404 is what a WRONG DEBUG_TOKEN looks like: the gate closes the"
      note "      route rather than admitting it is there. Check the value you set."
    else
      warn "  /debug/$route -> $code"
      head -c 300 "/tmp/uno-debug.$$" 2>/dev/null | sed 's/^/      /'
      printf '\n'
    fi
    rm -f "/tmp/uno-debug.$$"
  done
else
  SKIPPED+=("the /debug/* verification")
fi
unset DEBUG_VALUE
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The Gmail lane — all four, or none"
say "send_email is off unless ALL FOUR are set. Three of four is worse than"
say "zero: the lane stays off and there are dangling secrets to explain later,"
say "so this sets four or it sets nothing."
say ""
GMAIL_KEYS=(GMAIL_SENDER GMAIL_CLIENT_ID GMAIL_CLIENT_SECRET GMAIL_REFRESH_TOKEN)
GMAIL_HAVE=0
for k in "${GMAIL_KEYS[@]}"; do already_set "$k" && GMAIL_HAVE=$((GMAIL_HAVE + 1)); done
if [[ "$GMAIL_HAVE" -eq 4 ]]; then
  note "✓ All four already set."
elif ! confirm "Set up the Gmail lane now? (n leaves it off, which is the current state)"; then
  note "Skipped. send_email stays off and fails gracefully, as it does today."
  SKIPPED+=("Gmail lane — send_email stays off")
else
  [[ "$GMAIL_HAVE" -gt 0 ]] && warn "$GMAIL_HAVE of 4 are already set; you will be asked for all four."
  say ""
  say "Two of these come from a Google Cloud OAuth CLIENT, and the third from a"
  say "consent round done once by hand. The Gmail API must be enabled on the"
  say "project first or the token exchange returns a 403 that reads like a"
  say "credential problem and is not one."
  say ""
  step "1. Enable the Gmail API on the project:"
  open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
  pause "Enabled? Enter to continue"
  step "2. Credentials -> Create credentials -> OAuth client ID -> Web application."
  step "   Add https://developers.google.com/oauthplayground as an authorized"
  step "   redirect URI: the playground is how the refresh token gets minted."
  open_url "https://console.cloud.google.com/apis/credentials"
  ask GMAIL_SENDER_V "The From address (the mailbox this sends AS):"
  ask GMAIL_CLIENT_ID_V "OAuth client ID:"
  ask_secret GMAIL_CLIENT_SECRET_V "OAuth client secret (hidden):"
  say ""
  step "3. In the playground: the gear -> Use your own OAuth credentials, paste"
  step "   the same id and secret. Scope:"
  note "     https://www.googleapis.com/auth/gmail.send"
  step "   Authorize, then Exchange authorization code for tokens."
  warn "You want the REFRESH token, not the access token. The access token"
  warn "expires in an hour; the refresh token is the one worth storing."
  open_url "https://developers.google.com/oauthplayground/"
  ask_secret GMAIL_REFRESH_TOKEN_V "Refresh token (hidden):"

  if [[ -z "$GMAIL_SENDER_V" || -z "$GMAIL_CLIENT_ID_V" || -z "$GMAIL_CLIENT_SECRET_V" || -z "$GMAIL_REFRESH_TOKEN_V" ]]; then
    warn "One or more was blank. Setting NONE of them — three of four is the"
    warn "state this stage exists to avoid."
    SKIPPED+=("Gmail lane — incomplete, nothing written")
  else
    for pair in "GMAIL_SENDER:$GMAIL_SENDER_V" "GMAIL_CLIENT_ID:$GMAIL_CLIENT_ID_V" \
                "GMAIL_CLIENT_SECRET:$GMAIL_CLIENT_SECRET_V" "GMAIL_REFRESH_TOKEN:$GMAIL_REFRESH_TOKEN_V"; do
      if printf '%s' "${pair#*:}" | put_secret "${pair%%:*}"; then
        WRITTEN_SECRET+=("${pair%%:*}")
      else
        SKIPPED+=("${pair%%:*}")
      fi
    done
    say ""
    confirm "Redeploy so the lane comes up?" && { deploy_bot || warn "Deploy failed; the secrets are still set."; }
  fi
  unset GMAIL_SENDER_V GMAIL_CLIENT_ID_V GMAIL_CLIENT_SECRET_V GMAIL_REFRESH_TOKEN_V
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Repoint the Slack app — the slowest step, and the only unscriptable one"
say "pkce_enabled permanently disables apps.manifest.update for this app"
say "(ADR-024), so the manifests in the repo are the paste source and the"
say "rollback point. Nothing here can make Slack agree."
say ""
open_url "https://app.slack.com/app-settings/$SLACK_TEAM/$SLACK_APP/app-manifest"
step "Paste agents/uno-bot/slack-app-manifest.yaml, save."
step "Then agents/uno-bot/slack-app-manifest-commands.yaml, save."
step "Check Event Subscriptions and Interactivity both show the new host."
step "Check OAuth & Permissions -> Redirect URLs matches EXACTLY:"
note "    $ORIGIN/oauth/slack/callback"
warn "Slack compares that string character for character."
pause "Pasted and saved? Enter to verify"
confirm "Run 'npm run slack:diff'?" && { ( cd "$BOT_DIR" && npm run slack:diff ) || warn "Differences above. The LIVE app is what matters — fix it there."; }
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The deploy token, on the environment and not the repo"
say "CI deploys with this. It goes on the uno-bot-production ENVIRONMENT:"
say "a repo-level token is readable by any workflow that omits 'environment:',"
say "which is the whole reason that environment exists (#310)."
say ""
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token -> 'Edit Cloudflare Workers' template."
step "Account Resources: THIS account only ($ACCOUNT). Zone Resources: none."
step "Create, then copy — Cloudflare shows it once."
ask_secret CF_TOKEN "Paste the API token (hidden):"
if [[ -n "$CF_TOKEN" ]]; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$CF_TOKEN" | gh secret set CLOUDFLARE_API_TOKEN --env uno-bot-production >/dev/null 2>&1; then
      printf '  %s✓ set%s CLOUDFLARE_API_TOKEN on uno-bot-production\n' "$GREEN" "$RESET"
      WRITTEN_SECRET+=("CLOUDFLARE_API_TOKEN (uno-bot-production)")
    else
      SKIPPED+=("CLOUDFLARE_API_TOKEN — gh secret set CLOUDFLARE_API_TOKEN --env uno-bot-production")
      warn "gh refused it. Set it by hand before merging."
    fi
  else
    SKIPPED+=("CLOUDFLARE_API_TOKEN — gh is not authenticated")
    warn "gh not ready."
  fi
else
  SKIPPED+=("CLOUDFLARE_API_TOKEN")
fi
unset CF_TOKEN
say ""
step "Also point CI's health checks at the new host — a variable, not a commit:"
confirm "Set vars.UNO_BOT_WORKER_URL to $ORIGIN?" && set_var UNO_BOT_WORKER_URL "$ORIGIN"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify, then merge"
say "The old host must appear nowhere it should not. This scan ignores the"
say "ALLOWED list, so it is proof the move is COMPLETE and not merely permitted."
( cd "$BOT_DIR" && node scripts/check-worker-host.mjs ) || warn "Findings above."
say ""
( cd "$BOT_DIR" && npm run --silent secrets:audit ) || true
say ""
step "A real Slack thread: ask uno something, expect a grounded answer with links."
step "Then, and only then:"
note "    gh pr create --base main --head $BRANCH"
warn "Merging DEPLOYS. Do not merge until the thread above answered correctly."
pause

finish
