#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the three secrets `npm run secrets:set` cannot take by prompt.
#
# WHY A SECOND WIZARD. `set-secrets.mjs` asks with echo off, which is right for
# a single-line token and wrong for two of these:
#
#   * GEMINI_SA_PRIVATE_KEY is a multi-line PEM. A no-echo prompt cannot
#     honestly take a pasted key block, so set-secrets skips it and prints a
#     command instead — and the command needs the human to know that the value
#     lives under `.private_key` in a service-account JSON and that its \n
#     escapes must become real newlines first. That is three chances to get it
#     wrong, and the wrong version fails at RUNTIME with a signing error, not
#     at deploy.
#
#     So this asks for the PATH. A path is not a secret; it can be typed in the
#     clear, tab-completed, and checked before anything is sent. The key is
#     extracted and piped straight into wrangler on stdin: never echoed, never
#     written to disk, never in argv (visible to `ps`), never in shell history.
#
#   * SUPABASE_ANON_KEY and SLACK_MCP_CLIENT_SECRET are single-line and CAN be
#     prompted — set-secrets calls them optional, which is why they were passed
#     over. They are set on the account being left, so leaving them unset here
#     is a downgrade rather than a cutover. This opens the exact page each one
#     is on rather than describing where to look.
#
# RUN IT FROM agents/uno-bot ON THE CUTOVER BRANCH: wrangler.toml is what names
# the account, so the branch decides which Worker these land on.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

BOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$BOT_DIR/../.." && pwd)"
cd "$BOT_DIR"

WRANGLER="$BOT_DIR/node_modules/.bin/wrangler"
[[ -x "$WRANGLER" ]] || WRANGLER="wrangler"

ACCOUNT="$(sed -n 's/^account_id *= *"\(.*\)"/\1/p' "$BOT_DIR/wrangler.toml" | head -n1)"

# put_secret NAME — reads the VALUE on stdin and hands it to wrangler there.
# Never an argv entry: argv is readable by `ps` for every user on the machine.
# It only REPORTS. The bookkeeping arrays are appended by the caller, because
# the right-hand side of a pipeline runs in a subshell and an array grown in
# there is discarded when it exits — the closing summary would come out empty
# while every secret had in fact landed.
put_secret() {
  local name="$1"
  if "$WRANGLER" secret put "$name" >/dev/null 2>&1; then
    printf '  %s✓ set%s %s on the Worker in %s\n' "$GREEN" "$RESET" "$name" "$ACCOUNT"
    return 0
  fi
  warn "wrangler refused $name. Nothing was written."
  return 1
}

# already_set NAME — true when the Worker already carries it, so a re-run skips
# rather than asking again.
already_set() {
  "$WRANGLER" secret list 2>/dev/null | grep -q "\"$1\""
}

banner "uno-bot: the last three secrets (#288)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "These land on the Worker named by wrangler.toml in this directory."
note "account: $ACCOUNT"
note "branch:  $(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD)"
if ! command -v node >/dev/null 2>&1; then warn "node is missing."; exit 1; fi
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
if [[ "$NODE_MAJOR" -lt 22 ]]; then
  warn "node $(node -v) — wrangler needs v22+. Run 'nvm use 22' and re-run."
  exit 1
fi
note "✓ node $(node -v)"
say ""
say "Already on the Worker:"
"$WRANGLER" secret list 2>/dev/null | node -e "
  let s=''; process.stdin.on('data',c=>s+=c).on('end',()=>{
    try { JSON.parse(s.slice(s.indexOf('['))).forEach(x=>console.log('    · '+x.name)); }
    catch { console.log('    (could not read the list)'); }
  });"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GEMINI_SA_PRIVATE_KEY — from the service-account JSON"
if already_set GEMINI_SA_PRIVATE_KEY; then
  note "Already set. Skipping."
else
  say "This is the ONE that blocks everything: without it the Worker cannot"
  say "reach Vertex, which is the model lane (ADR-018)."
  say ""
  say "You do not paste anything here. Give the PATH to the service-account"
  say "JSON you downloaded from Google Cloud — the file with \"type\":"
  say "\"service_account\" in it. Drag the file into this terminal to fill the"
  say "path in, or paste it."
  say ""
  ask SA_JSON_PATH "Path to the service-account JSON:"
  # Drag-and-drop leaves a trailing space and shell-escapes; a quoted paste
  # leaves the quotes. Both are the normal way this gets typed.
  SA_JSON_PATH="${SA_JSON_PATH%\"}"; SA_JSON_PATH="${SA_JSON_PATH#\"}"
  SA_JSON_PATH="${SA_JSON_PATH%\'}"; SA_JSON_PATH="${SA_JSON_PATH#\'}"
  SA_JSON_PATH="$(printf '%s' "$SA_JSON_PATH" | sed 's/[[:space:]]*$//; s/\\ / /g')"
  SA_JSON_PATH="${SA_JSON_PATH/#\~/$HOME}"

  if [[ ! -f "$SA_JSON_PATH" ]]; then
    warn "No file at: $SA_JSON_PATH"
    note "  Nothing was sent. Re-run when you have the path."
    exit 1
  fi

  # Read the file ONCE and report only what is safe to show: the type, the
  # project, the email, and whether a private_key is present. Never the key.
  SA_SUMMARY="$(node -e "
    const fs = require('fs');
    let d;
    try { d = JSON.parse(fs.readFileSync(process.argv[1], 'utf8')); }
    catch (e) { console.log('BAD_JSON'); process.exit(0); }
    if (d.type !== 'service_account') { console.log('NOT_SA:' + (d.type || 'no type field')); process.exit(0); }
    if (!d.private_key || !d.private_key.includes('BEGIN')) { console.log('NO_KEY'); process.exit(0); }
    console.log(['OK', d.client_email || '?', d.project_id || '?'].join('|'));
  " "$SA_JSON_PATH")"

  case "$SA_SUMMARY" in
    BAD_JSON) warn "That file is not valid JSON. Nothing sent."; exit 1 ;;
    NOT_SA:*) warn "That JSON is not a service account (type: ${SA_SUMMARY#NOT_SA:}). Nothing sent."
              note "  You want the key file from IAM & Admin -> Service Accounts -> Keys."; exit 1 ;;
    NO_KEY)   warn "No private_key in that JSON. Nothing sent."; exit 1 ;;
  esac

  SA_EMAIL="$(printf '%s' "$SA_SUMMARY" | cut -d'|' -f2)"
  SA_PROJECT="$(printf '%s' "$SA_SUMMARY" | cut -d'|' -f3)"
  say ""
  note "  service account: $SA_EMAIL"
  note "  project:         $SA_PROJECT"
  # GEMINI_PROJECT_ID is a plain var, so it CAN be read back and compared.
  WANT_PROJECT="$(sed -n 's/^GEMINI_PROJECT_ID *= *"\(.*\)"/\1/p' "$BOT_DIR/wrangler.toml" | head -n1)"
  if [[ -n "$WANT_PROJECT" && "$SA_PROJECT" != "$WANT_PROJECT" ]]; then
    warn "wrangler.toml expects project \"$WANT_PROJECT\", this key is for \"$SA_PROJECT\"."
    confirm "Send it anyway?" || { note "  Nothing sent."; exit 1; }
  fi
  say ""
  say "The private_key will be extracted with its \\n escapes turned into real"
  say "newlines and piped straight to wrangler. It is not printed, not written"
  say "anywhere, and not passed as an argument."
  if confirm "Set GEMINI_SA_PRIVATE_KEY from this file?"; then
    if node -e "
      const fs = require('fs');
      process.stdout.write(JSON.parse(fs.readFileSync(process.argv[1], 'utf8')).private_key);
    " "$SA_JSON_PATH" | put_secret GEMINI_SA_PRIVATE_KEY; then
      WRITTEN_SECRET+=("GEMINI_SA_PRIVATE_KEY")
    else
      SKIPPED+=("GEMINI_SA_PRIVATE_KEY")
    fi
  else
    SKIPPED+=("GEMINI_SA_PRIVATE_KEY")
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "SUPABASE_ANON_KEY"
if already_set SUPABASE_ANON_KEY; then
  note "Already set. Skipping."
else
  SUPA_URL="$(sed -n 's|^SUPABASE_URL *= *"https://\([^.]*\)\..*|\1|p' "$BOT_DIR/wrangler.toml" | head -n1)"
  say "wrangler.toml has SEMANTIC_SEARCH = on and BLUEPRINT_HYBRID = on against"
  say "project $SUPA_URL. Without this key both go dark — set-secrets calls it"
  say "optional because the Worker still BOOTS without it."
  say ""
  open_url "https://supabase.com/dashboard/project/$SUPA_URL/settings/api"
  step "Copy the anon / public key (the publishable one, NOT service_role)."
  warn "service_role bypasses row-level security. It is the wrong key here."
  ask_secret SUPABASE_ANON_KEY_VALUE "Paste the anon key (hidden):"
  if [[ -n "$SUPABASE_ANON_KEY_VALUE" ]]; then
    if printf '%s' "$SUPABASE_ANON_KEY_VALUE" | put_secret SUPABASE_ANON_KEY; then
      WRITTEN_SECRET+=("SUPABASE_ANON_KEY")
    else
      SKIPPED+=("SUPABASE_ANON_KEY")
    fi
  else
    note "  Empty. Nothing sent."
    SKIPPED+=("SUPABASE_ANON_KEY")
  fi
  unset SUPABASE_ANON_KEY_VALUE
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "SLACK_MCP_CLIENT_SECRET, then deploy"
if already_set SLACK_MCP_CLIENT_SECRET; then
  note "Already set. Skipping."
else
  say "The client half of the Slack MCP OAuth flow — workspace search."
  say ""
  open_url "https://api.slack.com/apps/A0APS0L8HJR/general"
  step "Basic Information -> App Credentials -> Client Secret -> Show."
  warn "Do NOT click Regenerate: the old Worker is still the live bot and"
  warn "shares this app."
  ask_secret SLACK_MCP_CLIENT_SECRET_VALUE "Paste the client secret (hidden):"
  if [[ -n "$SLACK_MCP_CLIENT_SECRET_VALUE" ]]; then
    if printf '%s' "$SLACK_MCP_CLIENT_SECRET_VALUE" | put_secret SLACK_MCP_CLIENT_SECRET; then
      WRITTEN_SECRET+=("SLACK_MCP_CLIENT_SECRET")
    else
      SKIPPED+=("SLACK_MCP_CLIENT_SECRET")
    fi
  else
    note "  Empty. Nothing sent."
    SKIPPED+=("SLACK_MCP_CLIENT_SECRET")
  fi
  unset SLACK_MCP_CLIENT_SECRET_VALUE
fi
say ""
say "Secrets only take effect on the NEXT deploy."
if confirm "Deploy now?"; then
  ( cd "$BOT_DIR" && npm run deploy ) || warn "Deploy failed. Read it above; the secrets are still set."
else
  SKIPPED+=("deploy (npm run deploy from agents/uno-bot)")
fi
say ""
say "The whole picture:"
( cd "$BOT_DIR" && npm run --silent secrets:audit ) || true

finish
