/**
 * Prototype Market catalog data.
 *
 * Each entry represents one deployed (or deployable) prototype.
 * Designers add their own entry via the /po:post skill or manually here.
 *
 * PRODUCT_PILLARS and STAGES are the canonical filter value sets;
 * keep card data consistent with these.
 */

export const STAGES = ['low', 'mid', 'high'];

export const PRODUCT_PILLARS = [
  'admin',
  'home',
  'login',
  'profile',
  'toolkit',
  'training',
  'universal',
];

export const STAGE_META = {
  low:  { label: 'Low-fi',  badgeStyle: 'warning' },
  mid:  { label: 'Mid-fi',  badgeStyle: 'info' },
  high: { label: 'High-fi', badgeStyle: 'success' },
};

export const PILLAR_META = {
  admin:     { label: 'Admin',     badgeStyle: 'primary' },
  home:      { label: 'Home',      badgeStyle: 'secondary' },
  login:     { label: 'Login',     badgeStyle: 'tertiary' },
  profile:   { label: 'Profile',   badgeStyle: 'tertiary' },
  toolkit:   { label: 'Toolkit',   badgeStyle: 'secondary' },
  training:  { label: 'Training',  badgeStyle: 'primary' },
  universal: { label: 'Universal', badgeStyle: 'tertiary' },
};

export const prototypes = [
  {
    id: 'home-redesign',
    title: 'Home Redesign (Dashboard)',
    description:
      'New student dashboard with tutoring performance radar, weekly tutoring load donut, student momentum charts, and personalized training carousel.',
    deploymentUrl: null,
    notionCardUrl: 'https://www.notion.so/example-card-id',
    notionCardId: 'PLUS-42',
    stage: 'high',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'home',
    localPath: '/home',
    repoPath: 'playground/home-redesign/',
  },
  {
    id: 'research-assistant-chat',
    title: 'Research Assistant Chat',
    description:
      'AI-powered research assistant for tutors using @assistant-ui/react with strategy heatmaps, training progress, and chat interface.',
    deploymentUrl: null,
    notionCardUrl: 'https://www.notion.so/example-card-id-2',
    notionCardId: 'PLUS-58',
    stage: 'high',
    lastUpdated: '2026-03-08',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/research-assistant',
    repoPath: 'playground/research-assistant-chat/',
  },
  {
    id: 'in-session-ux',
    title: 'In-Session & Reflection',
    description:
      'In-session view with student management, reflection assistant, and manage-assignment modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-05',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'toolkit',
    localPath: '/sessions',
    repoPath: 'playground/in-session-ux/',
  },
  {
    id: 'monthly-report',
    title: 'Monthly Reports',
    description:
      'Tutor monthly performance reports list and detail view with metrics and progress indicators.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-28',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/monthly-reports',
    repoPath: 'playground/monthly-report/',
  },
  {
    id: 'weekly-report-demo',
    title: 'Weekly Report Demo',
    description:
      'Weekly report page and list view for tutor performance summaries.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-20',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/weekly-report-demo/',
  },
  {
    id: 'session-management',
    title: 'Sessions Management',
    description:
      'Sessions page with session cards, attendance modal with attended/absent badges, and edit session modal with tutor/student rosters.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-25',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: null,
    repoPath: 'playground/session-management/',
  },
  {
    id: 'tutor-performance',
    title: 'Tutor Performance',
    description:
      'Tutor Admin performance page with attendance/sign-up donut charts, sortable tutor table, and click-to-open attendance modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-22',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/tutor-performance/',
  },
  {
    id: 'training-progress',
    title: 'Training Progress',
    description:
      'Tutor Admin training progress page with completion/accuracy metrics, tutor table with progress rings, and lesson details modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-18',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'training',
    localPath: null,
    repoPath: 'playground/training-progress/',
  },
  {
    id: 'fill-in-flow',
    title: 'Fill-In Flow',
    description:
      'Session fill-in request and approval flow for covering open session slots.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-15',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: null,
    repoPath: 'playground/fill-in-flow/',
  },
  {
    id: 'sidebar-iteration',
    title: 'Sidebar Iteration',
    description:
      'Navigation sidebar redesign iterations for the toolkit section IA revision.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-03-17',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'universal',
    localPath: null,
    repoPath: 'playground/sidebar-iteration/',
  },
  {
    id: 'group-modal',
    title: 'Group Modal',
    description:
      'Group Admin modal for adding/editing a group with name, school select, multi-select tutors, and group size fields.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-15',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/group-modal/',
  },
  {
    id: 'group-performance-v2',
    title: 'Group Performance v2',
    description:
      'Group Admin performance page with attendance pie chart, session distribution stacked bar, tutor table with color-coded badges, and pagination.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-12',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/group-performance-v2/',
  },
  {
    id: 'tutor-risk-interventions',
    title: 'Tutor Risk & Interventions',
    description:
      'Tutor Admin risk page with at-risk stats, trend line chart, interventions bar chart, filter controls, and 20-row data table.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-14',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/tutor-risk-interventions/',
  },
  {
    id: 'tutor-reflection-form',
    title: 'Tutor Reflection Form',
    description:
      'Redesigned post-session reflection form with one-form-per-session flow, adaptive branching, student deep dive, strategy effectiveness ratings, and escalation tracking.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-03-19',
    creators: ['Bryan'],
    contributors: ['Bryan'],
    productPillar: 'toolkit',
    localPath: null,
    repoPath: 'playground/tutor-reflection-form/',
  },
  {
    id: 'storybook-ai-agent',
    title: 'Storybook AI Agent',
    description:
      'AI-powered Storybook automation agent for component documentation and testing.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'low',
    lastUpdated: '2026-02-10',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'universal',
    localPath: null,
    repoPath: 'playground/storybook-ai-agent/',
  },
];
