/**
 * Prototype Market catalog data.
 *
 * Each entry represents one deployed (or deployable) prototype.
 * Designers add their own entry via the /uno:post skill or manually here.
 *
 * PRODUCT_PILLARS and STAGES are the canonical filter value sets;
 * keep card data consistent with these.
 */

export const STAGES = ['low', 'mid', 'high'];

export const PRODUCT_PILLARS = [
  'admin',
  'home',
  'login',
  'profile',
  'toolkit',
  'training',
  'universal',
];

export const STAGE_META = {
  low:  { label: 'Low-fi',  badgeStyle: 'warning' },
  mid:  { label: 'Mid-fi',  badgeStyle: 'info' },
  high: { label: 'High-fi', badgeStyle: 'success' },
};

export const PILLAR_META = {
  admin:     { label: 'Admin',     badgeStyle: 'primary' },
  home:      { label: 'Home',      badgeStyle: 'secondary' },
  login:     { label: 'Login',     badgeStyle: 'tertiary' },
  profile:   { label: 'Profile',   badgeStyle: 'tertiary' },
  toolkit:   { label: 'Toolkit',   badgeStyle: 'secondary' },
  training:  { label: 'Training',  badgeStyle: 'primary' },
  universal: { label: 'Universal', badgeStyle: 'tertiary' },
};

export const prototypes = [
  {
    id: '1001',
    title: 'Redesigned Homepage',
    description:
      'The new student dashboard with progress cards, tutoring performance radar, weekly load donut, student momentum charts, and personalized training carousel.',
    deploymentUrl: null,
    notionCardUrl: 'https://www.notion.so/example-card-id',
    notionCardId: 'PLUS-42',
    stage: 'high',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'home',
    localPath: '/1001',
    repoPath: 'playground/home-redesign/',
    loomVideoUrl: 'https://www.loom.com/share/example123',
  },
  {
    id: '1002',
    title: 'Tutor Admin',
    description:
      'Admin view for managing tutors and training progress, with compliance monitoring and performance tables.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/1002',
    repoPath: 'playground/home-redesign/',
  },
  {
    id: '1003',
    title: 'Sessions',
    description:
      'In-session view with student cards, assignment management, chat tools, and real-time engagement tracking.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'toolkit',
    localPath: '/1003',
    repoPath: 'playground/home-redesign/',
  },
  {
    id: '1004',
    title: 'Session Reflection',
    description:
      'Post-session reflection assistant with AI-guided prompts, student progress review, and strategy recommendations.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'toolkit',
    localPath: '/1004',
    repoPath: 'playground/home-redesign/',
  },
  {
    id: '1005',
    title: 'Lessons Simulator',
    description:
      'A growth mindset simulation game where tutors practice responding to challenging student scenarios.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-03-10',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'training',
    localPath: '/1005',
    repoPath: 'playground/home-redesign/',
  },
  {
    id: '1006',
    title: 'Research Assistant Chat',
    description:
      'AI-powered research assistant for tutors using @assistant-ui/react with strategy heatmaps, training progress, and chat interface.',
    deploymentUrl: null,
    notionCardUrl: 'https://www.notion.so/example-card-id-2',
    notionCardId: 'PLUS-58',
    stage: 'high',
    lastUpdated: '2026-03-08',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/1006',
    repoPath: 'playground/research-assistant-chat/',
  },
  {
    id: '1007',
    title: 'In-Session & Reflection',
    description:
      'In-session view with student management, reflection assistant, and manage-assignment modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-05',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'toolkit',
    localPath: null,
    repoPath: 'playground/in-session-ux/',
  },
  {
    id: '1008',
    title: 'Monthly Reports',
    description:
      'Tutor monthly performance reports list and detail view with metrics and progress indicators.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-28',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/1008',
    repoPath: 'playground/monthly-report/',
  },
  {
    id: '1009',
    title: 'Weekly Report Demo',
    description:
      'Weekly report page and list view for tutor performance summaries.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-20',
    creators: ['Bill'],
    contributors: ['Bill'],
    productPillar: 'admin',
    localPath: '/1009',
    repoPath: 'playground/weekly-report-demo/',
  },
  {
    id: '1010',
    title: 'Sessions Management',
    description:
      'Sessions page with session cards, attendance modal with attended/absent badges, and edit session modal with tutor/student rosters.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-25',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: '/1010',
    repoPath: 'playground/session-management/',
  },
  {
    id: '1011',
    title: 'Tutor Performance',
    description:
      'Tutor Admin performance page with attendance/sign-up donut charts, sortable tutor table, and click-to-open attendance modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-22',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'admin',
    localPath: '/1011',
    repoPath: 'playground/tutor-performance/',
  },
  {
    id: '1012',
    title: 'Training Progress',
    description:
      'Tutor Admin training progress page with completion/accuracy metrics, tutor table with progress rings, and lesson details modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-18',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'training',
    localPath: '/1012',
    repoPath: 'playground/training-progress/',
  },
  {
    id: '1013',
    title: 'Fill-In Flow',
    description:
      'Session fill-in request and approval flow for covering open session slots.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-15',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: '/1013',
    repoPath: 'playground/fill-in-flow/',
  },
  {
    id: '1014',
    title: 'Sidebar Iteration',
    description:
      'Navigation sidebar redesign iterations for the toolkit section IA revision.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-03-17',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'universal',
    localPath: '/1014',
    repoPath: 'playground/sidebar-iteration/',
  },
  {
    id: '1015',
    title: 'Group Modal',
    description:
      'Group Admin modal for adding/editing a group with name, school select, multi-select tutors, and group size fields.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-15',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/group-modal/',
  },
  {
    id: '1016',
    title: 'Group Performance v2',
    description:
      'Group Admin performance page with attendance pie chart, session distribution stacked bar, tutor table with color-coded badges, and pagination.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-12',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: '/1016',
    repoPath: 'playground/group-performance-v2/',
  },
  {
    id: '1017',
    title: 'Tutor Risk & Interventions',
    description:
      'Tutor Admin risk page with at-risk stats, trend line chart, interventions bar chart, filter controls, and 20-row data table.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'high',
    lastUpdated: '2026-03-14',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'admin',
    localPath: '/1017',
    repoPath: 'playground/tutor-risk-interventions/',
  },
  {
    id: '1019',
    title: 'Storybook AI Agent',
    description:
      'AI-powered Storybook automation agent for component documentation and testing.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'low',
    lastUpdated: '2026-02-10',
    creators: ['Ashley'],
    contributors: ['Ashley'],
    productPillar: 'universal',
    localPath: null,
    repoPath: 'playground/storybook-ai-agent/',
  },
  {
    id: '1020',
    title: 'Group Info',
    description:
      'Group information display and management interface.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'low',
    lastUpdated: '2026-02-10',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'admin',
    localPath: null,
    repoPath: 'playground/group-info/',
  },
  {
    id: '1021',
    title: 'Help Request Flow',
    description:
      'Student help request submission and tutor notification flow.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'low',
    lastUpdated: '2026-02-10',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: null,
    repoPath: 'playground/help-request-flow/',
  },
  {
    id: '1022',
    title: 'Recommend Sessions',
    description:
      'Session recommendation interface with tutor matching and session modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-15',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'toolkit',
    localPath: '/1022',
    repoPath: 'playground/recommend-sessions/',
  },
  {
    id: '1024',
    title: 'Student Goal Dashboard',
    description:
      'Session admin dashboard with student goals, session breakdown modal, and student assignment modal.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-20',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'admin',
    localPath: '/1024',
    repoPath: 'playground/student-goal-dashboard-flow/',
  },
  {
    id: '1025',
    title: 'Student Onboarding Wizard',
    description:
      'Multi-step student onboarding wizard with baseline assessment, schedule selection, and goal setting.',
    deploymentUrl: null,
    notionCardUrl: null,
    notionCardId: null,
    stage: 'mid',
    lastUpdated: '2026-02-18',
    creators: ['Victor'],
    contributors: ['Victor'],
    productPillar: 'training',
    localPath: '/1025',
    repoPath: 'playground/student-onboarding-wizard/',
  },
];
