import React from 'react';
import { expect, userEvent, within } from 'storybook/test';

import AiLabel, { AI_ORIGINS } from './AiLabel';

/**
 * `AiLabel` — identity and trust before chat (#269).
 *
 * THE TEST SEAM IS THIS FILE, as it was for `Tag` (#276): a good assertion here
 * is one a person could make by using the component — that the mark is not a
 * control, that a low-confidence mark says what to do about it, that the
 * accessible name carries the confidence — and never that a class name is
 * present.
 *
 * The contrast half is covered elsewhere and is not re-asserted: the a11y
 * ratchet in `docs/evals/a11y-baseline.json` tracks `color-contrast` over every
 * story rendered, and may fall but never rise.
 */
export default {
    title: 'Components/Status and loading/AI label',
    component: AiLabel,
    parameters: {
        docs: {
            description: {
                component:
                    'Marks content the agent produced, and says how much to trust it. The axis is '
                    + 'who authored the value — generated, assisted, reviewed — not whether a model '
                    + 'was involved somewhere.',
            },
        },
    },
};

const row = { display: 'flex', flexWrap: 'wrap', gap: '12px', alignItems: 'center' };

/** Every origin the API offers, each with its own default words. */
export const Origins = () => (
    <div style={{ ...row, flexDirection: 'column', alignItems: 'flex-start' }}>
        {AI_ORIGINS.map((origin) => (
            <AiLabel key={origin} origin={origin} />
        ))}
    </div>
);

/**
 * The mark is not a control.
 *
 * The same rule `Tag` and `Badge` both record: a button inside a button is
 * invalid per ARIA, so the label stays a `span` and exactly one control can
 * exist inside it. A caller who wants the whole row pressable wants a `Button`
 * with this inside it.
 */
export const TheMarkIsNotAControl = () => (
    <div style={row}>
        <AiLabel origin="generated" />
    </div>
);

TheMarkIsNotAControl.play = async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    await expect(canvas.queryAllByRole('button')).toHaveLength(0);
    await expect(canvas.getByRole('note')).toBeInTheDocument();
};

/**
 * Low confidence says what to do about it.
 *
 * #269 quotes Rovo's voice guidance: the system must "define… what happens when
 * confidence is low". A caution treatment with no instruction is a warning with
 * no instruction, so the note is part of the component and not left to each
 * caller's prose — it has a default, and the default is an instruction.
 */
export const LowConfidenceCarriesItsAdvice = () => (
    <div style={{ ...row, flexDirection: 'column', alignItems: 'flex-start' }}>
        <AiLabel origin="generated" confidence="low" />
        <AiLabel origin="assisted" confidence="low" note="Two of these citations could not be verified" />
    </div>
);

LowConfidenceCarriesItsAdvice.play = async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const marks = canvas.getAllByRole('note');
    await expect(marks).toHaveLength(2);
    // The default is an instruction, not a label.
    await expect(marks[0]).toHaveTextContent(/check this before relying on it/i);
    await expect(marks[1]).toHaveTextContent(/could not be verified/i);
};

/**
 * The accessible name carries the confidence.
 *
 * A screen-reader user who is told "Generated by PLUS AI" and nothing else has
 * been told the same thing whether or not the system trusts its own output.
 * `AiIndicator`, the surface this replaces, is labelled "AI-powered feature" —
 * the category of the thing, and nothing about the content it is attached to.
 */
export const ConfidenceIsInTheName = () => (
    <div style={row}>
        <AiLabel origin="generated" confidence="low" />
    </div>
);

ConfidenceIsInTheName.play = async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const mark = canvas.getByRole('note');
    await expect(mark).toHaveAttribute(
        'aria-label',
        expect.stringContaining('low confidence'),
    );
};

/**
 * The explain affordance is a real button, and it says what it DOES.
 *
 * `RecommendedLessons` today carries `title="AI recommended"`, which is not a
 * reliable accessible name in any screen reader. A control has to be a control.
 */
export const ExplainIsARealButton = () => {
    const [asked, setAsked] = React.useState(false);
    return (
        <div style={{ ...row, flexDirection: 'column', alignItems: 'flex-start' }}>
            <AiLabel origin="generated" onExplain={() => setAsked(true)} />
            <span className="body3-txt">{asked ? 'Explained' : 'Not asked'}</span>
        </div>
    );
};

ExplainIsARealButton.play = async ({ canvasElement }) => {
    const canvas = within(canvasElement);
    const button = canvas.getByRole('button', { name: 'How was this made?' });
    await userEvent.click(button);
    await expect(canvas.getByText('Explained')).toBeInTheDocument();
};

/**
 * The icon is decoration, not content.
 *
 * It repeats what the mark already says in words. Announcing it would give a
 * screen-reader user "wand, Generated by PLUS AI" and no extra information —
 * the same rule `Tag`'s swatch follows.
 */
export const TheGlyphIsDecoration = () => (
    <div style={row}>
        <AiLabel origin="assisted" />
    </div>
);

TheGlyphIsDecoration.play = async ({ canvasElement }) => {
    const mark = canvasElement.querySelector('.plus-ai-label__mark');
    await expect(mark).toHaveAttribute('aria-hidden', 'true');
};

/**
 * No brand hue is picked here.
 *
 * Atlassian's `color.rovo.background.brand.bold` is #000000: AI is a different
 * REGISTER, not another semantic colour competing with success and danger. The
 * accent is one local custom property with a neutral token behind it, so the
 * branding decision #269 leaves open lands on one declaration and nothing else
 * moves.
 *
 * This asserts the absence, because the absence is the design: nothing in the
 * component may resolve to `--color-primary`, which is what the surface it
 * replaces hard-codes as `fill="#0472A8"`.
 */
export const NoBrandHueIsAssumed = () => (
    <div style={row}>
        <AiLabel origin="generated" />
    </div>
);

NoBrandHueIsAssumed.play = async ({ canvasElement }) => {
    const mark = canvasElement.querySelector('.plus-ai-label');
    const styles = getComputedStyle(mark);
    const primary = getComputedStyle(document.documentElement)
        .getPropertyValue('--color-primary')
        .trim();
    const accent = styles.getPropertyValue('--plus-ai-accent').trim();
    await expect(accent, 'the accent must be a real value').not.toBe('');
    await expect(
        accent.toLowerCase(),
        'the AI mark must not borrow the primary action colour',
    ).not.toBe(primary.toLowerCase());
};

/* -------------------------------------------------------------- playground */

export const Interactive = (args) => <AiLabel {...args} onExplain={() => {}} />;
Interactive.args = {
    origin: 'generated',
    confidence: 'high',
    text: '',
    note: '',
};
