import React from 'react';
import PropTypes from 'prop-types';
import './AiLabel.scss';

/**
 * `AiLabel` — this came from the agent, and here is how much to trust it (#269).
 *
 * WHY IT EXISTS, MEASURED. The product already has AI surfaces. It has four,
 * each invented locally, and they do not agree about anything:
 *
 *   AiIndicator (Training/Lessons)      sparkle SVG with fill="#0472A8" — the
 *                                       primary blue, HARD-CODED as a literal.
 *                                       So the AI mark is the same colour as an
 *                                       ordinary primary action.
 *   AiPromptedQuestionBox (Toolkit)     --color-mastering-content-state-16 — a
 *                                       CURRICULUM DOMAIN colour, borrowed for a
 *                                       meaning it does not have.
 *   RecommendedLessons (Home)           its own class, and `title="AI
 *                                       recommended"` as the whole accessible
 *                                       story.
 *   AlertForSupervisors (Training)      prose, no mark at all.
 *
 * Three marks, three colours, none of them shared. That is #269's argument with
 * the evidence attached, and it is why this is a component rather than a fifth
 * local one.
 *
 * NO BRAND HUE IS PICKED HERE, ON PURPOSE. #269 says the colour is Bill's call
 * and this file does not make it. What it does take from Atlassian's Rovo — read
 * from `@atlaskit/tokens` and recorded on #269 — are the three decisions that
 * are NOT about which hue:
 *
 *   1. THE BOLD GROUND IS ACHROMATIC. `color.rovo.background.brand.bold` is
 *      #000000. AI is a different REGISTER, not another semantic colour
 *      competing with success and danger — so this uses the neutral surface
 *      ramp the system already has, and adding a hue later changes one token.
 *   2. THE ACCENT IS ONLY EVER A BORDER AND AN ICON. Rovo has no `rovo.text`
 *      and no `rovo.background` in its accent hues: the identity marks an edge
 *      and a glyph, it never floods a surface. So does this.
 *   3. LOW CONFIDENCE IS A STATE, NOT A FOOTNOTE. Rovo's voice guidance is
 *      explicit that the system must "define… what happens when confidence is
 *      low", so `confidence="low"` is part of the API and carries a required
 *      note rather than being left to each caller's prose.
 *
 * WHO AUTHORED THE VALUE IS THE AXIS, which is the same test `Tag` and `Badge`
 * split on (#276). `generated` is the agent's own output; `assisted` is a person's
 * work the agent helped with; `reviewed` is agent output a person has since
 * checked. A reader needs those three separated far more than they need to know
 * a model was involved somewhere.
 */

export const AI_ORIGINS = ['generated', 'assisted', 'reviewed'];
export const AI_CONFIDENCE = ['high', 'low'];

/** What each origin says, when the caller gives no text of its own. */
const DEFAULT_TEXT = {
    generated: 'Generated by PLUS AI',
    assisted: 'Written with PLUS AI',
    reviewed: 'AI draft, reviewed',
};

/**
 * The accessible name has to say what the mark MEANS, not what it is.
 *
 * `AiIndicator` today is labelled "AI-powered feature", which tells a
 * screen-reader user the category of the thing and nothing about the content it
 * is attached to. `RecommendedLessons` uses a `title` attribute, which is not a
 * reliable accessible name at all.
 */
const CONFIDENCE_SUFFIX = {
    high: '',
    low: ' — low confidence, check before relying on it',
};

export const AiLabel = ({
    children,
    text,
    origin = 'generated',
    confidence = 'high',
    note,
    onExplain,
    explainLabel = 'How was this made?',
    className = '',
    id,
    ...rest
}) => {
    const label = children ?? text ?? DEFAULT_TEXT[origin] ?? DEFAULT_TEXT.generated;
    const lowConfidence = confidence === 'low';

    /*
     * The label is not a control, and the explain affordance is.
     *
     * Same rule as `Tag` and `Badge`: a button inside a button is invalid per
     * ARIA, so the mark stays a `span` and exactly one control can exist inside
     * it. A caller who wants the whole row to be pressable wants a `Button`
     * with this inside it, not this with a handler on it.
     */
    const classes = [
        'plus-ai-label',
        `plus-ai-label--${origin}`,
        lowConfidence ? 'plus-ai-label--low' : '',
        className,
    ].filter(Boolean).join(' ');

    return (
        <span
            id={id}
            className={classes}
            // The whole mark is one thing to a screen reader — the icon, the
            // words, and the confidence, in that order and as one phrase.
            role="note"
            aria-label={`${typeof label === 'string' ? label : 'AI attribution'}${CONFIDENCE_SUFFIX[confidence] ?? ''}`}
            {...rest}
        >
            {/*
              * Decision 2: the accent is a glyph and an edge. The icon is
              * decorative because the words beside it already say what it means
              * — announcing "wand" would add a shape, not information.
              */}
            <i className="fa-solid fa-wand-magic-sparkles plus-ai-label__mark" aria-hidden="true" />
            <span className="plus-ai-label__text body3-txt">{label}</span>
            {lowConfidence && (
                <span className="plus-ai-label__note body3-txt">
                    {/*
                      * The note is REQUIRED by propTypes when confidence is low,
                      * and defaulted here as well: a low-confidence mark with no
                      * advice is a warning with no instruction, which is the
                      * thing #269 quotes Rovo's guidance against.
                      */}
                    {note ?? 'Check this before relying on it'}
                </span>
            )}
            {onExplain && (
                <button
                    type="button"
                    className="plus-ai-label__explain"
                    onClick={onExplain}
                >
                    {explainLabel}
                </button>
            )}
        </span>
    );
};

AiLabel.propTypes = {
    /** The label (takes precedence over `text`). */
    children: PropTypes.node,
    /** The label, as a string. Defaults per `origin`. */
    text: PropTypes.string,
    /** Who authored the value — the axis that matters, not whether a model was involved. */
    origin: PropTypes.oneOf(AI_ORIGINS),
    /** `low` adds the caution treatment and the note. */
    confidence: PropTypes.oneOf(AI_CONFIDENCE),
    /** What to do about low confidence. Shown only when `confidence` is `low`. */
    note: PropTypes.string,
    /** Renders a real button inside the mark. The mark itself is never a control. */
    onExplain: PropTypes.func,
    /** The explain button's own words. It says what it DOES. */
    explainLabel: PropTypes.string,
    className: PropTypes.string,
    id: PropTypes.string,
};

export default AiLabel;
